//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPHCM: &lt;b style=&quot;color: rgb(2, 101, 203);&quot;&gt;174/47 Thái Phiên, P8, Q11, ĐT: 0903.71.20.70 - 0908.61.21.40&lt;/b&gt;.
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà Nội: &lt;b style=&quot;color: rgb(2, 101, 203);&quot;&gt;A2-CN8 - Xuân Phương - Từ Liêm, ĐT: 0904.92.72.56 - 0126.24.88.0.88.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://phukienipadx.com.
        /// </summary>
        internal static string BackLink {
            get {
                return ResourceManager.GetString("BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mr. Đạt) 0903.71.20.70.
        /// </summary>
        internal static string UserSupport1 {
            get {
                return ResourceManager.GetString("UserSupport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mr. Hùng) 0908.61.21.40.
        /// </summary>
        internal static string UserSupport2 {
            get {
                return ResourceManager.GetString("UserSupport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Mr. Minh) 0904.92.72.56 -
        ///0126.24.88.0.88.
        /// </summary>
        internal static string UserSupport3 {
            get {
                return ResourceManager.GetString("UserSupport3", resourceCulture);
            }
        }
    }
}
