//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table ezpages 
    /// </summary>
    public partial class ezpagesModel 
    {
        #region Ctor

        // Default contructor
        public ezpagesModel()
        {
            this.IsNewItem = true;
            this._ezpages = new ezpages();
        }

        // Default contructor that set entity to field
        public ezpagesModel(ezpages ezpages)
        {
        	this._ezpages = ezpages;
            this._pages__id = ezpages.pages_id;
            this._languages__id = ezpages.languages_id;
            this._pages__title = ezpages.pages_title;
            this._alt__url = ezpages.alt_url;
            this._alt__url__external = ezpages.alt_url_external;
            this._pages__html__text = ezpages.pages_html_text;
            this._status__header = ezpages.status_header;
            this._status__sidebox = ezpages.status_sidebox;
            this._status__footer = ezpages.status_footer;
            this._status__toc = ezpages.status_toc;
            this._header__sort__order = ezpages.header_sort_order;
            this._sidebox__sort__order = ezpages.sidebox_sort_order;
            this._footer__sort__order = ezpages.footer_sort_order;
            this._toc__sort__order = ezpages.toc_sort_order;
            this._page__open__new__window = ezpages.page_open_new_window;
            this._page__is__ssl = ezpages.page_is_ssl;
            this._toc__chapter = ezpages.toc_chapter;
            this._originalezpages = ezpages.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private ezpages _ezpages;
        private ezpages _originalezpages;
        
        public ezpages Mapezpages()
        {
            this._ezpages.pages_id = this._pages__id;
            this._ezpages.languages_id = this._languages__id;
            this._ezpages.pages_title = this._pages__title;
            this._ezpages.alt_url = this._alt__url;
            this._ezpages.alt_url_external = this._alt__url__external;
            this._ezpages.pages_html_text = this._pages__html__text;
            this._ezpages.status_header = this._status__header;
            this._ezpages.status_sidebox = this._status__sidebox;
            this._ezpages.status_footer = this._status__footer;
            this._ezpages.status_toc = this._status__toc;
            this._ezpages.header_sort_order = this._header__sort__order;
            this._ezpages.sidebox_sort_order = this._sidebox__sort__order;
            this._ezpages.footer_sort_order = this._footer__sort__order;
            this._ezpages.toc_sort_order = this._toc__sort__order;
            this._ezpages.page_open_new_window = this._page__open__new__window;
            this._ezpages.page_is_ssl = this._page__is__ssl;
            this._ezpages.toc_chapter = this._toc__chapter;
        	return _ezpages;
        }
        
        public void Undo()
        {
            if(this._originalezpages == null) return;
            this._pages__id = this._originalezpages.pages_id;
            this._languages__id = this._originalezpages.languages_id;
            this._pages__title = this._originalezpages.pages_title;
            this._alt__url = this._originalezpages.alt_url;
            this._alt__url__external = this._originalezpages.alt_url_external;
            this._pages__html__text = this._originalezpages.pages_html_text;
            this._status__header = this._originalezpages.status_header;
            this._status__sidebox = this._originalezpages.status_sidebox;
            this._status__footer = this._originalezpages.status_footer;
            this._status__toc = this._originalezpages.status_toc;
            this._header__sort__order = this._originalezpages.header_sort_order;
            this._sidebox__sort__order = this._originalezpages.sidebox_sort_order;
            this._footer__sort__order = this._originalezpages.footer_sort_order;
            this._toc__sort__order = this._originalezpages.toc_sort_order;
            this._page__open__new__window = this._originalezpages.page_open_new_window;
            this._page__is__ssl = this._originalezpages.page_is_ssl;
            this._toc__chapter = this._originalezpages.toc_chapter;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalezpages == null) return;
            this._ezpages.pages_id = this._originalezpages.pages_id;
            this._ezpages.languages_id = this._originalezpages.languages_id;
            this._ezpages.pages_title = this._originalezpages.pages_title;
            this._ezpages.alt_url = this._originalezpages.alt_url;
            this._ezpages.alt_url_external = this._originalezpages.alt_url_external;
            this._ezpages.pages_html_text = this._originalezpages.pages_html_text;
            this._ezpages.status_header = this._originalezpages.status_header;
            this._ezpages.status_sidebox = this._originalezpages.status_sidebox;
            this._ezpages.status_footer = this._originalezpages.status_footer;
            this._ezpages.status_toc = this._originalezpages.status_toc;
            this._ezpages.header_sort_order = this._originalezpages.header_sort_order;
            this._ezpages.sidebox_sort_order = this._originalezpages.sidebox_sort_order;
            this._ezpages.footer_sort_order = this._originalezpages.footer_sort_order;
            this._ezpages.toc_sort_order = this._originalezpages.toc_sort_order;
            this._ezpages.page_open_new_window = this._originalezpages.page_open_new_window;
            this._ezpages.page_is_ssl = this._originalezpages.page_is_ssl;
            this._ezpages.toc_chapter = this._originalezpages.toc_chapter;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _pages__id;
        public int pages_id
        {
            get { return this._pages__id; }
            set
            {
                if (this._pages__id != value)
                {
                    this.IsDirty = true;
                    this._pages__id = value;
                }
            }
        }
        
        private int _languages__id;
        public int languages_id
        {
            get { return this._languages__id; }
            set
            {
                if (this._languages__id != value)
                {
                    this.IsDirty = true;
                    this._languages__id = value;
                }
            }
        }
        
        private string _pages__title;
        public string pages_title
        {
            get { return this._pages__title; }
            set
            {
                if (this._pages__title != value)
                {
                    this.IsDirty = true;
                    this._pages__title = value;
                }
            }
        }
        
        private string _alt__url;
        public string alt_url
        {
            get { return this._alt__url; }
            set
            {
                if (this._alt__url != value)
                {
                    this.IsDirty = true;
                    this._alt__url = value;
                }
            }
        }
        
        private string _alt__url__external;
        public string alt_url_external
        {
            get { return this._alt__url__external; }
            set
            {
                if (this._alt__url__external != value)
                {
                    this.IsDirty = true;
                    this._alt__url__external = value;
                }
            }
        }
        
        private string _pages__html__text;
        public string pages_html_text
        {
            get { return this._pages__html__text; }
            set
            {
                if (this._pages__html__text != value)
                {
                    this.IsDirty = true;
                    this._pages__html__text = value;
                }
            }
        }
        
        private int _status__header;
        public int status_header
        {
            get { return this._status__header; }
            set
            {
                if (this._status__header != value)
                {
                    this.IsDirty = true;
                    this._status__header = value;
                }
            }
        }
        
        private int _status__sidebox;
        public int status_sidebox
        {
            get { return this._status__sidebox; }
            set
            {
                if (this._status__sidebox != value)
                {
                    this.IsDirty = true;
                    this._status__sidebox = value;
                }
            }
        }
        
        private int _status__footer;
        public int status_footer
        {
            get { return this._status__footer; }
            set
            {
                if (this._status__footer != value)
                {
                    this.IsDirty = true;
                    this._status__footer = value;
                }
            }
        }
        
        private int _status__toc;
        public int status_toc
        {
            get { return this._status__toc; }
            set
            {
                if (this._status__toc != value)
                {
                    this.IsDirty = true;
                    this._status__toc = value;
                }
            }
        }
        
        private int _header__sort__order;
        public int header_sort_order
        {
            get { return this._header__sort__order; }
            set
            {
                if (this._header__sort__order != value)
                {
                    this.IsDirty = true;
                    this._header__sort__order = value;
                }
            }
        }
        
        private int _sidebox__sort__order;
        public int sidebox_sort_order
        {
            get { return this._sidebox__sort__order; }
            set
            {
                if (this._sidebox__sort__order != value)
                {
                    this.IsDirty = true;
                    this._sidebox__sort__order = value;
                }
            }
        }
        
        private int _footer__sort__order;
        public int footer_sort_order
        {
            get { return this._footer__sort__order; }
            set
            {
                if (this._footer__sort__order != value)
                {
                    this.IsDirty = true;
                    this._footer__sort__order = value;
                }
            }
        }
        
        private int _toc__sort__order;
        public int toc_sort_order
        {
            get { return this._toc__sort__order; }
            set
            {
                if (this._toc__sort__order != value)
                {
                    this.IsDirty = true;
                    this._toc__sort__order = value;
                }
            }
        }
        
        private int _page__open__new__window;
        public int page_open_new_window
        {
            get { return this._page__open__new__window; }
            set
            {
                if (this._page__open__new__window != value)
                {
                    this.IsDirty = true;
                    this._page__open__new__window = value;
                }
            }
        }
        
        private int _page__is__ssl;
        public int page_is_ssl
        {
            get { return this._page__is__ssl; }
            set
            {
                if (this._page__is__ssl != value)
                {
                    this.IsDirty = true;
                    this._page__is__ssl = value;
                }
            }
        }
        
        private int _toc__chapter;
        public int toc_chapter
        {
            get { return this._toc__chapter; }
            set
            {
                if (this._toc__chapter != value)
                {
                    this.IsDirty = true;
                    this._toc__chapter = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
