//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table manufacturer 
    /// </summary>
    public partial class manufacturerModel 
    {
        #region Ctor

        // Default contructor
        public manufacturerModel()
        {
            this.IsNewItem = true;
            this._manufacturer = new manufacturer();
        }

        // Default contructor that set entity to field
        public manufacturerModel(manufacturer manufacturer)
        {
        	this._manufacturer = manufacturer;
            this._manufacturers__id = manufacturer.manufacturers_id;
            this._manufacturers__name = manufacturer.manufacturers_name;
            this._manufacturers__image = manufacturer.manufacturers_image;
            this._date__added = manufacturer.date_added;
            this._last__modified = manufacturer.last_modified;
            this._originalmanufacturer = manufacturer.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private manufacturer _manufacturer;
        private manufacturer _originalmanufacturer;
        
        public manufacturer Mapmanufacturer()
        {
            this._manufacturer.manufacturers_id = this._manufacturers__id;
            this._manufacturer.manufacturers_name = this._manufacturers__name;
            this._manufacturer.manufacturers_image = this._manufacturers__image;
            this._manufacturer.date_added = this._date__added;
            this._manufacturer.last_modified = this._last__modified;
        	return _manufacturer;
        }
        
        public void Undo()
        {
            if(this._originalmanufacturer == null) return;
            this._manufacturers__id = this._originalmanufacturer.manufacturers_id;
            this._manufacturers__name = this._originalmanufacturer.manufacturers_name;
            this._manufacturers__image = this._originalmanufacturer.manufacturers_image;
            this._date__added = this._originalmanufacturer.date_added;
            this._last__modified = this._originalmanufacturer.last_modified;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalmanufacturer == null) return;
            this._manufacturer.manufacturers_id = this._originalmanufacturer.manufacturers_id;
            this._manufacturer.manufacturers_name = this._originalmanufacturer.manufacturers_name;
            this._manufacturer.manufacturers_image = this._originalmanufacturer.manufacturers_image;
            this._manufacturer.date_added = this._originalmanufacturer.date_added;
            this._manufacturer.last_modified = this._originalmanufacturer.last_modified;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _manufacturers__id;
        public int manufacturers_id
        {
            get { return this._manufacturers__id; }
            set
            {
                if (this._manufacturers__id != value)
                {
                    this.IsDirty = true;
                    this._manufacturers__id = value;
                }
            }
        }
        
        private string _manufacturers__name;
        public string manufacturers_name
        {
            get { return this._manufacturers__name; }
            set
            {
                if (this._manufacturers__name != value)
                {
                    this.IsDirty = true;
                    this._manufacturers__name = value;
                }
            }
        }
        
        private string _manufacturers__image;
        public string manufacturers_image
        {
            get { return this._manufacturers__image; }
            set
            {
                if (this._manufacturers__image != value)
                {
                    this.IsDirty = true;
                    this._manufacturers__image = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _date__added;
        public Nullable<System.DateTime> date_added
        {
            get { return this._date__added; }
            set
            {
                if (this._date__added != value)
                {
                    this.IsDirty = true;
                    this._date__added = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _last__modified;
        public Nullable<System.DateTime> last_modified
        {
            get { return this._last__modified; }
            set
            {
                if (this._last__modified != value)
                {
                    this.IsDirty = true;
                    this._last__modified = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
