//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table orders_status_history 
    /// </summary>
    public partial class orders_status_historyModel 
    {
        #region Ctor

        // Default contructor
        public orders_status_historyModel()
        {
            this.IsNewItem = true;
            this._orders__status__history = new orders_status_history();
        }

        // Default contructor that set entity to field
        public orders_status_historyModel(orders_status_history orders_status_history)
        {
        	this._orders__status__history = orders_status_history;
            this._orders__status__history__id = orders_status_history.orders_status_history_id;
            this._orders__id = orders_status_history.orders_id;
            this._orders__status__id = orders_status_history.orders_status_id;
            this._date__added = orders_status_history.date_added;
            this._customer__notified = orders_status_history.customer_notified;
            this._comments = orders_status_history.comments;
            this._originalorders_status_history = orders_status_history.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private orders_status_history _orders__status__history;
        private orders_status_history _originalorders_status_history;
        
        public orders_status_history Maporders_status_history()
        {
            this._orders__status__history.orders_status_history_id = this._orders__status__history__id;
            this._orders__status__history.orders_id = this._orders__id;
            this._orders__status__history.orders_status_id = this._orders__status__id;
            this._orders__status__history.date_added = this._date__added;
            this._orders__status__history.customer_notified = this._customer__notified;
            this._orders__status__history.comments = this._comments;
        	return _orders__status__history;
        }
        
        public void Undo()
        {
            if(this._originalorders_status_history == null) return;
            this._orders__status__history__id = this._originalorders_status_history.orders_status_history_id;
            this._orders__id = this._originalorders_status_history.orders_id;
            this._orders__status__id = this._originalorders_status_history.orders_status_id;
            this._date__added = this._originalorders_status_history.date_added;
            this._customer__notified = this._originalorders_status_history.customer_notified;
            this._comments = this._originalorders_status_history.comments;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalorders_status_history == null) return;
            this._orders__status__history.orders_status_history_id = this._originalorders_status_history.orders_status_history_id;
            this._orders__status__history.orders_id = this._originalorders_status_history.orders_id;
            this._orders__status__history.orders_status_id = this._originalorders_status_history.orders_status_id;
            this._orders__status__history.date_added = this._originalorders_status_history.date_added;
            this._orders__status__history.customer_notified = this._originalorders_status_history.customer_notified;
            this._orders__status__history.comments = this._originalorders_status_history.comments;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _orders__status__history__id;
        public int orders_status_history_id
        {
            get { return this._orders__status__history__id; }
            set
            {
                if (this._orders__status__history__id != value)
                {
                    this.IsDirty = true;
                    this._orders__status__history__id = value;
                }
            }
        }
        
        private int _orders__id;
        public int orders_id
        {
            get { return this._orders__id; }
            set
            {
                if (this._orders__id != value)
                {
                    this.IsDirty = true;
                    this._orders__id = value;
                }
            }
        }
        
        private int _orders__status__id;
        public int orders_status_id
        {
            get { return this._orders__status__id; }
            set
            {
                if (this._orders__status__id != value)
                {
                    this.IsDirty = true;
                    this._orders__status__id = value;
                }
            }
        }
        
        private System.DateTime _date__added;
        public System.DateTime date_added
        {
            get { return this._date__added; }
            set
            {
                if (this._date__added != value)
                {
                    this.IsDirty = true;
                    this._date__added = value;
                }
            }
        }
        
        private Nullable<int> _customer__notified;
        public Nullable<int> customer_notified
        {
            get { return this._customer__notified; }
            set
            {
                if (this._customer__notified != value)
                {
                    this.IsDirty = true;
                    this._customer__notified = value;
                }
            }
        }
        
        private string _comments;
        public string comments
        {
            get { return this._comments; }
            set
            {
                if (this._comments != value)
                {
                    this.IsDirty = true;
                    this._comments = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
