//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table orders 
    /// </summary>
    public partial class ordersModel 
    {
        #region Ctor

        // Default contructor
        public ordersModel()
        {
            this.IsNewItem = true;
            this._orders = new orders();
        }

        // Default contructor that set entity to field
        public ordersModel(orders orders)
        {
        	this._orders = orders;
            this._orders__id = orders.orders_id;
            this._customers__id = orders.customers_id;
            this._customers__name = orders.customers_name;
            this._customers__company = orders.customers_company;
            this._customers__street__address = orders.customers_street_address;
            this._customers__suburb = orders.customers_suburb;
            this._customers__city = orders.customers_city;
            this._customers__postcode = orders.customers_postcode;
            this._customers__state = orders.customers_state;
            this._customers__country = orders.customers_country;
            this._customers__telephone = orders.customers_telephone;
            this._customers__email__address = orders.customers_email_address;
            this._customers__address__format__id = orders.customers_address_format_id;
            this._delivery__name = orders.delivery_name;
            this._delivery__company = orders.delivery_company;
            this._delivery__street__address = orders.delivery_street_address;
            this._delivery__suburb = orders.delivery_suburb;
            this._delivery__city = orders.delivery_city;
            this._delivery__postcode = orders.delivery_postcode;
            this._delivery__state = orders.delivery_state;
            this._delivery__country = orders.delivery_country;
            this._delivery__address__format__id = orders.delivery_address_format_id;
            this._billing__name = orders.billing_name;
            this._billing__company = orders.billing_company;
            this._billing__street__address = orders.billing_street_address;
            this._billing__suburb = orders.billing_suburb;
            this._billing__city = orders.billing_city;
            this._billing__postcode = orders.billing_postcode;
            this._billing__state = orders.billing_state;
            this._billing__country = orders.billing_country;
            this._billing__address__format__id = orders.billing_address_format_id;
            this._payment__method = orders.payment_method;
            this._payment__module__code = orders.payment_module_code;
            this._shipping__method = orders.shipping_method;
            this._shipping__module__code = orders.shipping_module_code;
            this._coupon__code = orders.coupon_code;
            this._cc__type = orders.cc_type;
            this._cc__owner = orders.cc_owner;
            this._cc__number = orders.cc_number;
            this._cc__expires = orders.cc_expires;
            this._cc__cvv = orders.cc_cvv;
            this._last__modified = orders.last_modified;
            this._date__purchased = orders.date_purchased;
            this._orders__status = orders.orders_status;
            this._orders__date__finished = orders.orders_date_finished;
            this._currency = orders.currency;
            this._currency__value = orders.currency_value;
            this._order__total = orders.order_total;
            this._order__tax = orders.order_tax;
            this._paypal__ipn__id = orders.paypal_ipn_id;
            this._ip__address = orders.ip_address;
            this._originalorders = orders.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private orders _orders;
        private orders _originalorders;
        
        public orders Maporders()
        {
            this._orders.orders_id = this._orders__id;
            this._orders.customers_id = this._customers__id;
            this._orders.customers_name = this._customers__name;
            this._orders.customers_company = this._customers__company;
            this._orders.customers_street_address = this._customers__street__address;
            this._orders.customers_suburb = this._customers__suburb;
            this._orders.customers_city = this._customers__city;
            this._orders.customers_postcode = this._customers__postcode;
            this._orders.customers_state = this._customers__state;
            this._orders.customers_country = this._customers__country;
            this._orders.customers_telephone = this._customers__telephone;
            this._orders.customers_email_address = this._customers__email__address;
            this._orders.customers_address_format_id = this._customers__address__format__id;
            this._orders.delivery_name = this._delivery__name;
            this._orders.delivery_company = this._delivery__company;
            this._orders.delivery_street_address = this._delivery__street__address;
            this._orders.delivery_suburb = this._delivery__suburb;
            this._orders.delivery_city = this._delivery__city;
            this._orders.delivery_postcode = this._delivery__postcode;
            this._orders.delivery_state = this._delivery__state;
            this._orders.delivery_country = this._delivery__country;
            this._orders.delivery_address_format_id = this._delivery__address__format__id;
            this._orders.billing_name = this._billing__name;
            this._orders.billing_company = this._billing__company;
            this._orders.billing_street_address = this._billing__street__address;
            this._orders.billing_suburb = this._billing__suburb;
            this._orders.billing_city = this._billing__city;
            this._orders.billing_postcode = this._billing__postcode;
            this._orders.billing_state = this._billing__state;
            this._orders.billing_country = this._billing__country;
            this._orders.billing_address_format_id = this._billing__address__format__id;
            this._orders.payment_method = this._payment__method;
            this._orders.payment_module_code = this._payment__module__code;
            this._orders.shipping_method = this._shipping__method;
            this._orders.shipping_module_code = this._shipping__module__code;
            this._orders.coupon_code = this._coupon__code;
            this._orders.cc_type = this._cc__type;
            this._orders.cc_owner = this._cc__owner;
            this._orders.cc_number = this._cc__number;
            this._orders.cc_expires = this._cc__expires;
            this._orders.cc_cvv = this._cc__cvv;
            this._orders.last_modified = this._last__modified;
            this._orders.date_purchased = this._date__purchased;
            this._orders.orders_status = this._orders__status;
            this._orders.orders_date_finished = this._orders__date__finished;
            this._orders.currency = this._currency;
            this._orders.currency_value = this._currency__value;
            this._orders.order_total = this._order__total;
            this._orders.order_tax = this._order__tax;
            this._orders.paypal_ipn_id = this._paypal__ipn__id;
            this._orders.ip_address = this._ip__address;
        	return _orders;
        }
        
        public void Undo()
        {
            if(this._originalorders == null) return;
            this._orders__id = this._originalorders.orders_id;
            this._customers__id = this._originalorders.customers_id;
            this._customers__name = this._originalorders.customers_name;
            this._customers__company = this._originalorders.customers_company;
            this._customers__street__address = this._originalorders.customers_street_address;
            this._customers__suburb = this._originalorders.customers_suburb;
            this._customers__city = this._originalorders.customers_city;
            this._customers__postcode = this._originalorders.customers_postcode;
            this._customers__state = this._originalorders.customers_state;
            this._customers__country = this._originalorders.customers_country;
            this._customers__telephone = this._originalorders.customers_telephone;
            this._customers__email__address = this._originalorders.customers_email_address;
            this._customers__address__format__id = this._originalorders.customers_address_format_id;
            this._delivery__name = this._originalorders.delivery_name;
            this._delivery__company = this._originalorders.delivery_company;
            this._delivery__street__address = this._originalorders.delivery_street_address;
            this._delivery__suburb = this._originalorders.delivery_suburb;
            this._delivery__city = this._originalorders.delivery_city;
            this._delivery__postcode = this._originalorders.delivery_postcode;
            this._delivery__state = this._originalorders.delivery_state;
            this._delivery__country = this._originalorders.delivery_country;
            this._delivery__address__format__id = this._originalorders.delivery_address_format_id;
            this._billing__name = this._originalorders.billing_name;
            this._billing__company = this._originalorders.billing_company;
            this._billing__street__address = this._originalorders.billing_street_address;
            this._billing__suburb = this._originalorders.billing_suburb;
            this._billing__city = this._originalorders.billing_city;
            this._billing__postcode = this._originalorders.billing_postcode;
            this._billing__state = this._originalorders.billing_state;
            this._billing__country = this._originalorders.billing_country;
            this._billing__address__format__id = this._originalorders.billing_address_format_id;
            this._payment__method = this._originalorders.payment_method;
            this._payment__module__code = this._originalorders.payment_module_code;
            this._shipping__method = this._originalorders.shipping_method;
            this._shipping__module__code = this._originalorders.shipping_module_code;
            this._coupon__code = this._originalorders.coupon_code;
            this._cc__type = this._originalorders.cc_type;
            this._cc__owner = this._originalorders.cc_owner;
            this._cc__number = this._originalorders.cc_number;
            this._cc__expires = this._originalorders.cc_expires;
            this._cc__cvv = this._originalorders.cc_cvv;
            this._last__modified = this._originalorders.last_modified;
            this._date__purchased = this._originalorders.date_purchased;
            this._orders__status = this._originalorders.orders_status;
            this._orders__date__finished = this._originalorders.orders_date_finished;
            this._currency = this._originalorders.currency;
            this._currency__value = this._originalorders.currency_value;
            this._order__total = this._originalorders.order_total;
            this._order__tax = this._originalorders.order_tax;
            this._paypal__ipn__id = this._originalorders.paypal_ipn_id;
            this._ip__address = this._originalorders.ip_address;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalorders == null) return;
            this._orders.orders_id = this._originalorders.orders_id;
            this._orders.customers_id = this._originalorders.customers_id;
            this._orders.customers_name = this._originalorders.customers_name;
            this._orders.customers_company = this._originalorders.customers_company;
            this._orders.customers_street_address = this._originalorders.customers_street_address;
            this._orders.customers_suburb = this._originalorders.customers_suburb;
            this._orders.customers_city = this._originalorders.customers_city;
            this._orders.customers_postcode = this._originalorders.customers_postcode;
            this._orders.customers_state = this._originalorders.customers_state;
            this._orders.customers_country = this._originalorders.customers_country;
            this._orders.customers_telephone = this._originalorders.customers_telephone;
            this._orders.customers_email_address = this._originalorders.customers_email_address;
            this._orders.customers_address_format_id = this._originalorders.customers_address_format_id;
            this._orders.delivery_name = this._originalorders.delivery_name;
            this._orders.delivery_company = this._originalorders.delivery_company;
            this._orders.delivery_street_address = this._originalorders.delivery_street_address;
            this._orders.delivery_suburb = this._originalorders.delivery_suburb;
            this._orders.delivery_city = this._originalorders.delivery_city;
            this._orders.delivery_postcode = this._originalorders.delivery_postcode;
            this._orders.delivery_state = this._originalorders.delivery_state;
            this._orders.delivery_country = this._originalorders.delivery_country;
            this._orders.delivery_address_format_id = this._originalorders.delivery_address_format_id;
            this._orders.billing_name = this._originalorders.billing_name;
            this._orders.billing_company = this._originalorders.billing_company;
            this._orders.billing_street_address = this._originalorders.billing_street_address;
            this._orders.billing_suburb = this._originalorders.billing_suburb;
            this._orders.billing_city = this._originalorders.billing_city;
            this._orders.billing_postcode = this._originalorders.billing_postcode;
            this._orders.billing_state = this._originalorders.billing_state;
            this._orders.billing_country = this._originalorders.billing_country;
            this._orders.billing_address_format_id = this._originalorders.billing_address_format_id;
            this._orders.payment_method = this._originalorders.payment_method;
            this._orders.payment_module_code = this._originalorders.payment_module_code;
            this._orders.shipping_method = this._originalorders.shipping_method;
            this._orders.shipping_module_code = this._originalorders.shipping_module_code;
            this._orders.coupon_code = this._originalorders.coupon_code;
            this._orders.cc_type = this._originalorders.cc_type;
            this._orders.cc_owner = this._originalorders.cc_owner;
            this._orders.cc_number = this._originalorders.cc_number;
            this._orders.cc_expires = this._originalorders.cc_expires;
            this._orders.cc_cvv = this._originalorders.cc_cvv;
            this._orders.last_modified = this._originalorders.last_modified;
            this._orders.date_purchased = this._originalorders.date_purchased;
            this._orders.orders_status = this._originalorders.orders_status;
            this._orders.orders_date_finished = this._originalorders.orders_date_finished;
            this._orders.currency = this._originalorders.currency;
            this._orders.currency_value = this._originalorders.currency_value;
            this._orders.order_total = this._originalorders.order_total;
            this._orders.order_tax = this._originalorders.order_tax;
            this._orders.paypal_ipn_id = this._originalorders.paypal_ipn_id;
            this._orders.ip_address = this._originalorders.ip_address;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _orders__id;
        public int orders_id
        {
            get { return this._orders__id; }
            set
            {
                if (this._orders__id != value)
                {
                    this.IsDirty = true;
                    this._orders__id = value;
                }
            }
        }
        
        private int _customers__id;
        public int customers_id
        {
            get { return this._customers__id; }
            set
            {
                if (this._customers__id != value)
                {
                    this.IsDirty = true;
                    this._customers__id = value;
                }
            }
        }
        
        private string _customers__name;
        public string customers_name
        {
            get { return this._customers__name; }
            set
            {
                if (this._customers__name != value)
                {
                    this.IsDirty = true;
                    this._customers__name = value;
                }
            }
        }
        
        private string _customers__company;
        public string customers_company
        {
            get { return this._customers__company; }
            set
            {
                if (this._customers__company != value)
                {
                    this.IsDirty = true;
                    this._customers__company = value;
                }
            }
        }
        
        private string _customers__street__address;
        public string customers_street_address
        {
            get { return this._customers__street__address; }
            set
            {
                if (this._customers__street__address != value)
                {
                    this.IsDirty = true;
                    this._customers__street__address = value;
                }
            }
        }
        
        private string _customers__suburb;
        public string customers_suburb
        {
            get { return this._customers__suburb; }
            set
            {
                if (this._customers__suburb != value)
                {
                    this.IsDirty = true;
                    this._customers__suburb = value;
                }
            }
        }
        
        private string _customers__city;
        public string customers_city
        {
            get { return this._customers__city; }
            set
            {
                if (this._customers__city != value)
                {
                    this.IsDirty = true;
                    this._customers__city = value;
                }
            }
        }
        
        private string _customers__postcode;
        public string customers_postcode
        {
            get { return this._customers__postcode; }
            set
            {
                if (this._customers__postcode != value)
                {
                    this.IsDirty = true;
                    this._customers__postcode = value;
                }
            }
        }
        
        private string _customers__state;
        public string customers_state
        {
            get { return this._customers__state; }
            set
            {
                if (this._customers__state != value)
                {
                    this.IsDirty = true;
                    this._customers__state = value;
                }
            }
        }
        
        private string _customers__country;
        public string customers_country
        {
            get { return this._customers__country; }
            set
            {
                if (this._customers__country != value)
                {
                    this.IsDirty = true;
                    this._customers__country = value;
                }
            }
        }
        
        private string _customers__telephone;
        public string customers_telephone
        {
            get { return this._customers__telephone; }
            set
            {
                if (this._customers__telephone != value)
                {
                    this.IsDirty = true;
                    this._customers__telephone = value;
                }
            }
        }
        
        private string _customers__email__address;
        public string customers_email_address
        {
            get { return this._customers__email__address; }
            set
            {
                if (this._customers__email__address != value)
                {
                    this.IsDirty = true;
                    this._customers__email__address = value;
                }
            }
        }
        
        private int _customers__address__format__id;
        public int customers_address_format_id
        {
            get { return this._customers__address__format__id; }
            set
            {
                if (this._customers__address__format__id != value)
                {
                    this.IsDirty = true;
                    this._customers__address__format__id = value;
                }
            }
        }
        
        private string _delivery__name;
        public string delivery_name
        {
            get { return this._delivery__name; }
            set
            {
                if (this._delivery__name != value)
                {
                    this.IsDirty = true;
                    this._delivery__name = value;
                }
            }
        }
        
        private string _delivery__company;
        public string delivery_company
        {
            get { return this._delivery__company; }
            set
            {
                if (this._delivery__company != value)
                {
                    this.IsDirty = true;
                    this._delivery__company = value;
                }
            }
        }
        
        private string _delivery__street__address;
        public string delivery_street_address
        {
            get { return this._delivery__street__address; }
            set
            {
                if (this._delivery__street__address != value)
                {
                    this.IsDirty = true;
                    this._delivery__street__address = value;
                }
            }
        }
        
        private string _delivery__suburb;
        public string delivery_suburb
        {
            get { return this._delivery__suburb; }
            set
            {
                if (this._delivery__suburb != value)
                {
                    this.IsDirty = true;
                    this._delivery__suburb = value;
                }
            }
        }
        
        private string _delivery__city;
        public string delivery_city
        {
            get { return this._delivery__city; }
            set
            {
                if (this._delivery__city != value)
                {
                    this.IsDirty = true;
                    this._delivery__city = value;
                }
            }
        }
        
        private string _delivery__postcode;
        public string delivery_postcode
        {
            get { return this._delivery__postcode; }
            set
            {
                if (this._delivery__postcode != value)
                {
                    this.IsDirty = true;
                    this._delivery__postcode = value;
                }
            }
        }
        
        private string _delivery__state;
        public string delivery_state
        {
            get { return this._delivery__state; }
            set
            {
                if (this._delivery__state != value)
                {
                    this.IsDirty = true;
                    this._delivery__state = value;
                }
            }
        }
        
        private string _delivery__country;
        public string delivery_country
        {
            get { return this._delivery__country; }
            set
            {
                if (this._delivery__country != value)
                {
                    this.IsDirty = true;
                    this._delivery__country = value;
                }
            }
        }
        
        private int _delivery__address__format__id;
        public int delivery_address_format_id
        {
            get { return this._delivery__address__format__id; }
            set
            {
                if (this._delivery__address__format__id != value)
                {
                    this.IsDirty = true;
                    this._delivery__address__format__id = value;
                }
            }
        }
        
        private string _billing__name;
        public string billing_name
        {
            get { return this._billing__name; }
            set
            {
                if (this._billing__name != value)
                {
                    this.IsDirty = true;
                    this._billing__name = value;
                }
            }
        }
        
        private string _billing__company;
        public string billing_company
        {
            get { return this._billing__company; }
            set
            {
                if (this._billing__company != value)
                {
                    this.IsDirty = true;
                    this._billing__company = value;
                }
            }
        }
        
        private string _billing__street__address;
        public string billing_street_address
        {
            get { return this._billing__street__address; }
            set
            {
                if (this._billing__street__address != value)
                {
                    this.IsDirty = true;
                    this._billing__street__address = value;
                }
            }
        }
        
        private string _billing__suburb;
        public string billing_suburb
        {
            get { return this._billing__suburb; }
            set
            {
                if (this._billing__suburb != value)
                {
                    this.IsDirty = true;
                    this._billing__suburb = value;
                }
            }
        }
        
        private string _billing__city;
        public string billing_city
        {
            get { return this._billing__city; }
            set
            {
                if (this._billing__city != value)
                {
                    this.IsDirty = true;
                    this._billing__city = value;
                }
            }
        }
        
        private string _billing__postcode;
        public string billing_postcode
        {
            get { return this._billing__postcode; }
            set
            {
                if (this._billing__postcode != value)
                {
                    this.IsDirty = true;
                    this._billing__postcode = value;
                }
            }
        }
        
        private string _billing__state;
        public string billing_state
        {
            get { return this._billing__state; }
            set
            {
                if (this._billing__state != value)
                {
                    this.IsDirty = true;
                    this._billing__state = value;
                }
            }
        }
        
        private string _billing__country;
        public string billing_country
        {
            get { return this._billing__country; }
            set
            {
                if (this._billing__country != value)
                {
                    this.IsDirty = true;
                    this._billing__country = value;
                }
            }
        }
        
        private int _billing__address__format__id;
        public int billing_address_format_id
        {
            get { return this._billing__address__format__id; }
            set
            {
                if (this._billing__address__format__id != value)
                {
                    this.IsDirty = true;
                    this._billing__address__format__id = value;
                }
            }
        }
        
        private string _payment__method;
        public string payment_method
        {
            get { return this._payment__method; }
            set
            {
                if (this._payment__method != value)
                {
                    this.IsDirty = true;
                    this._payment__method = value;
                }
            }
        }
        
        private string _payment__module__code;
        public string payment_module_code
        {
            get { return this._payment__module__code; }
            set
            {
                if (this._payment__module__code != value)
                {
                    this.IsDirty = true;
                    this._payment__module__code = value;
                }
            }
        }
        
        private string _shipping__method;
        public string shipping_method
        {
            get { return this._shipping__method; }
            set
            {
                if (this._shipping__method != value)
                {
                    this.IsDirty = true;
                    this._shipping__method = value;
                }
            }
        }
        
        private string _shipping__module__code;
        public string shipping_module_code
        {
            get { return this._shipping__module__code; }
            set
            {
                if (this._shipping__module__code != value)
                {
                    this.IsDirty = true;
                    this._shipping__module__code = value;
                }
            }
        }
        
        private string _coupon__code;
        public string coupon_code
        {
            get { return this._coupon__code; }
            set
            {
                if (this._coupon__code != value)
                {
                    this.IsDirty = true;
                    this._coupon__code = value;
                }
            }
        }
        
        private string _cc__type;
        public string cc_type
        {
            get { return this._cc__type; }
            set
            {
                if (this._cc__type != value)
                {
                    this.IsDirty = true;
                    this._cc__type = value;
                }
            }
        }
        
        private string _cc__owner;
        public string cc_owner
        {
            get { return this._cc__owner; }
            set
            {
                if (this._cc__owner != value)
                {
                    this.IsDirty = true;
                    this._cc__owner = value;
                }
            }
        }
        
        private string _cc__number;
        public string cc_number
        {
            get { return this._cc__number; }
            set
            {
                if (this._cc__number != value)
                {
                    this.IsDirty = true;
                    this._cc__number = value;
                }
            }
        }
        
        private string _cc__expires;
        public string cc_expires
        {
            get { return this._cc__expires; }
            set
            {
                if (this._cc__expires != value)
                {
                    this.IsDirty = true;
                    this._cc__expires = value;
                }
            }
        }
        
        private byte[] _cc__cvv;
        public byte[] cc_cvv
        {
            get { return this._cc__cvv; }
            set
            {
                if (this._cc__cvv != value)
                {
                    this.IsDirty = true;
                    this._cc__cvv = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _last__modified;
        public Nullable<System.DateTime> last_modified
        {
            get { return this._last__modified; }
            set
            {
                if (this._last__modified != value)
                {
                    this.IsDirty = true;
                    this._last__modified = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _date__purchased;
        public Nullable<System.DateTime> date_purchased
        {
            get { return this._date__purchased; }
            set
            {
                if (this._date__purchased != value)
                {
                    this.IsDirty = true;
                    this._date__purchased = value;
                }
            }
        }
        
        private int _orders__status;
        public int orders_status
        {
            get { return this._orders__status; }
            set
            {
                if (this._orders__status != value)
                {
                    this.IsDirty = true;
                    this._orders__status = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _orders__date__finished;
        public Nullable<System.DateTime> orders_date_finished
        {
            get { return this._orders__date__finished; }
            set
            {
                if (this._orders__date__finished != value)
                {
                    this.IsDirty = true;
                    this._orders__date__finished = value;
                }
            }
        }
        
        private string _currency;
        public string currency
        {
            get { return this._currency; }
            set
            {
                if (this._currency != value)
                {
                    this.IsDirty = true;
                    this._currency = value;
                }
            }
        }
        
        private Nullable<decimal> _currency__value;
        public Nullable<decimal> currency_value
        {
            get { return this._currency__value; }
            set
            {
                if (this._currency__value != value)
                {
                    this.IsDirty = true;
                    this._currency__value = value;
                }
            }
        }
        
        private Nullable<decimal> _order__total;
        public Nullable<decimal> order_total
        {
            get { return this._order__total; }
            set
            {
                if (this._order__total != value)
                {
                    this.IsDirty = true;
                    this._order__total = value;
                }
            }
        }
        
        private Nullable<decimal> _order__tax;
        public Nullable<decimal> order_tax
        {
            get { return this._order__tax; }
            set
            {
                if (this._order__tax != value)
                {
                    this.IsDirty = true;
                    this._order__tax = value;
                }
            }
        }
        
        private int _paypal__ipn__id;
        public int paypal_ipn_id
        {
            get { return this._paypal__ipn__id; }
            set
            {
                if (this._paypal__ipn__id != value)
                {
                    this.IsDirty = true;
                    this._paypal__ipn__id = value;
                }
            }
        }
        
        private string _ip__address;
        public string ip_address
        {
            get { return this._ip__address; }
            set
            {
                if (this._ip__address != value)
                {
                    this.IsDirty = true;
                    this._ip__address = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
