//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table products_to_categories 
    /// </summary>
    public partial class products_to_categoriesModel 
    {
        #region Ctor

        // Default contructor
        public products_to_categoriesModel()
        {
            this.IsNewItem = true;
            this._products__to__categories = new products_to_categories();
        }

        // Default contructor that set entity to field
        public products_to_categoriesModel(products_to_categories products_to_categories)
        {
        	this._products__to__categories = products_to_categories;
            this._products__id = products_to_categories.products_id;
            this._categories__id = products_to_categories.categories_id;
            this._originalproducts_to_categories = products_to_categories.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private products_to_categories _products__to__categories;
        private products_to_categories _originalproducts_to_categories;
        
        public products_to_categories Mapproducts_to_categories()
        {
            this._products__to__categories.products_id = this._products__id;
            this._products__to__categories.categories_id = this._categories__id;
        	return _products__to__categories;
        }
        
        public void Undo()
        {
            if(this._originalproducts_to_categories == null) return;
            this._products__id = this._originalproducts_to_categories.products_id;
            this._categories__id = this._originalproducts_to_categories.categories_id;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalproducts_to_categories == null) return;
            this._products__to__categories.products_id = this._originalproducts_to_categories.products_id;
            this._products__to__categories.categories_id = this._originalproducts_to_categories.categories_id;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _products__id;
        public int products_id
        {
            get { return this._products__id; }
            set
            {
                if (this._products__id != value)
                {
                    this.IsDirty = true;
                    this._products__id = value;
                }
            }
        }
        
        private int _categories__id;
        public int categories_id
        {
            get { return this._categories__id; }
            set
            {
                if (this._categories__id != value)
                {
                    this.IsDirty = true;
                    this._categories__id = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
