//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Linq.Expressions;

namespace phukienipadx.Dal.Repository
{
    /// <summary>
    /// Repository for table admin 
    /// </summary>
    public partial class adminRepository
    {
        #region auto generate code

        #region variable define

        IUnitOfWork unitOfWork;
        public IUnitOfWork UOW { get { return unitOfWork; } }

        #endregion

        #region Ctor

        // Default contructor that creates an instance of unit of work
        public adminRepository()
        {
            if (null == unitOfWork)
                unitOfWork = new UnitOfWork();
        }

        // Constructor of an instance of unit of work
        public adminRepository(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }

        #endregion

        #region Basic C.R.U.D. operations

        // Query admin
        public IQueryable<admin> Queryadmin(Expression<Func<admin, bool>> expression)
        {
        	return unitOfWork.GetQuery<admin>(expression);
        }
        // List of all admin 
        public IList<admin> GetAlladmin()
        {
            return unitOfWork.GetAll<admin>();
        }

        // Find all admin 
        public IList<admin> Findadmin(Expression<Func<admin, bool>> expression)
        {
            return unitOfWork.Find<admin>(expression).ToList();
        }

        // Get single admin 
        public admin GetSingleadmin(Func<admin, bool> expression)
        {
            return unitOfWork.GetSingle<admin>(expression);
        }

        // Add a new admin 
        public admin Addadmin(admin _admin)
        {
            unitOfWork.Add<admin>(_admin);
            return _admin;
        }

        // Delete a existed admin 
        public void Deleteadmin(admin _admin)
        {
            unitOfWork.Delete<admin>(_admin);
        }

        // Delete batch a existed admin 
        public void DeleteBatchadmin(IEnumerable<admin> collection)
        {
        	foreach(var item in collection)
        	{
        		unitOfWork.Delete<admin>(item);
        	}
        }

        // Update a existed admin 
        public admin Updateadmin(admin _admin)
        {
            unitOfWork.Update<admin>(_admin);
            return _admin;
        }

        // Refresh an existed admin 
        public admin Refeshadmin(admin _admin)
        {
            unitOfWork.Refresh<admin>(_admin);
            return _admin;
        }

        // Refresh Alladmin 
        public void RefreshListadmin(IEnumerable<admin> list)
        {
            unitOfWork.RefreshList<admin>(list);
        }

        // Commit all changes 
        public void Commit()
        {
            unitOfWork.Commit();
        }

        #endregion

        #endregion

        #region all the custom code


        #endregion
    }
}
