//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table admin 
    /// </summary>
    public partial class adminModel 
    {
        #region Ctor

        // Default contructor
        public adminModel()
        {
            this.IsNewItem = true;
            this._admin = new admin();
        }

        // Default contructor that set entity to field
        public adminModel(admin admin)
        {
        	this._admin = admin;
            this._admin__id = admin.admin_id;
            this._admin__name = admin.admin_name;
            this._admin__email = admin.admin_email;
            this._admin__pass = admin.admin_pass;
            this._admin__level = admin.admin_level;
            this._originaladmin = admin.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private admin _admin;
        private admin _originaladmin;
        
        public admin Mapadmin()
        {
            this._admin.admin_id = this._admin__id;
            this._admin.admin_name = this._admin__name;
            this._admin.admin_email = this._admin__email;
            this._admin.admin_pass = this._admin__pass;
            this._admin.admin_level = this._admin__level;
        	return _admin;
        }
        
        public void Undo()
        {
            if(this._originaladmin == null) return;
            this._admin__id = this._originaladmin.admin_id;
            this._admin__name = this._originaladmin.admin_name;
            this._admin__email = this._originaladmin.admin_email;
            this._admin__pass = this._originaladmin.admin_pass;
            this._admin__level = this._originaladmin.admin_level;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originaladmin == null) return;
            this._admin.admin_id = this._originaladmin.admin_id;
            this._admin.admin_name = this._originaladmin.admin_name;
            this._admin.admin_email = this._originaladmin.admin_email;
            this._admin.admin_pass = this._originaladmin.admin_pass;
            this._admin.admin_level = this._originaladmin.admin_level;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _admin__id;
        public int admin_id
        {
            get { return this._admin__id; }
            set
            {
                if (this._admin__id != value)
                {
                    this.IsDirty = true;
                    this._admin__id = value;
                }
            }
        }
        
        private string _admin__name;
        public string admin_name
        {
            get { return this._admin__name; }
            set
            {
                if (this._admin__name != value)
                {
                    this.IsDirty = true;
                    this._admin__name = value;
                }
            }
        }
        
        private string _admin__email;
        public string admin_email
        {
            get { return this._admin__email; }
            set
            {
                if (this._admin__email != value)
                {
                    this.IsDirty = true;
                    this._admin__email = value;
                }
            }
        }
        
        private string _admin__pass;
        public string admin_pass
        {
            get { return this._admin__pass; }
            set
            {
                if (this._admin__pass != value)
                {
                    this.IsDirty = true;
                    this._admin__pass = value;
                }
            }
        }
        
        private short _admin__level;
        public short admin_level
        {
            get { return this._admin__level; }
            set
            {
                if (this._admin__level != value)
                {
                    this.IsDirty = true;
                    this._admin__level = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
