//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table categories 
    /// </summary>
    public partial class categoriesModel 
    {
        #region Ctor

        // Default contructor
        public categoriesModel()
        {
            this.IsNewItem = true;
            this._categories = new categories();
        }

        // Default contructor that set entity to field
        public categoriesModel(categories categories)
        {
        	this._categories = categories;
            this._categories__id = categories.categories_id;
            this._categories__image = categories.categories_image;
            this._parent__id = categories.parent_id;
            this._sort__order = categories.sort_order;
            this._date__added = categories.date_added;
            this._last__modified = categories.last_modified;
            this._categories__status = categories.categories_status;
            this._originalcategories = categories.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private categories _categories;
        private categories _originalcategories;
        
        public categories Mapcategories()
        {
            this._categories.categories_id = this._categories__id;
            this._categories.categories_image = this._categories__image;
            this._categories.parent_id = this._parent__id;
            this._categories.sort_order = this._sort__order;
            this._categories.date_added = this._date__added;
            this._categories.last_modified = this._last__modified;
            this._categories.categories_status = this._categories__status;
        	return _categories;
        }
        
        public void Undo()
        {
            if(this._originalcategories == null) return;
            this._categories__id = this._originalcategories.categories_id;
            this._categories__image = this._originalcategories.categories_image;
            this._parent__id = this._originalcategories.parent_id;
            this._sort__order = this._originalcategories.sort_order;
            this._date__added = this._originalcategories.date_added;
            this._last__modified = this._originalcategories.last_modified;
            this._categories__status = this._originalcategories.categories_status;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalcategories == null) return;
            this._categories.categories_id = this._originalcategories.categories_id;
            this._categories.categories_image = this._originalcategories.categories_image;
            this._categories.parent_id = this._originalcategories.parent_id;
            this._categories.sort_order = this._originalcategories.sort_order;
            this._categories.date_added = this._originalcategories.date_added;
            this._categories.last_modified = this._originalcategories.last_modified;
            this._categories.categories_status = this._originalcategories.categories_status;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _categories__id;
        public int categories_id
        {
            get { return this._categories__id; }
            set
            {
                if (this._categories__id != value)
                {
                    this.IsDirty = true;
                    this._categories__id = value;
                }
            }
        }
        
        private string _categories__image;
        public string categories_image
        {
            get { return this._categories__image; }
            set
            {
                if (this._categories__image != value)
                {
                    this.IsDirty = true;
                    this._categories__image = value;
                }
            }
        }
        
        private int _parent__id;
        public int parent_id
        {
            get { return this._parent__id; }
            set
            {
                if (this._parent__id != value)
                {
                    this.IsDirty = true;
                    this._parent__id = value;
                }
            }
        }
        
        private Nullable<int> _sort__order;
        public Nullable<int> sort_order
        {
            get { return this._sort__order; }
            set
            {
                if (this._sort__order != value)
                {
                    this.IsDirty = true;
                    this._sort__order = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _date__added;
        public Nullable<System.DateTime> date_added
        {
            get { return this._date__added; }
            set
            {
                if (this._date__added != value)
                {
                    this.IsDirty = true;
                    this._date__added = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _last__modified;
        public Nullable<System.DateTime> last_modified
        {
            get { return this._last__modified; }
            set
            {
                if (this._last__modified != value)
                {
                    this.IsDirty = true;
                    this._last__modified = value;
                }
            }
        }
        
        private short _categories__status;
        public short categories_status
        {
            get { return this._categories__status; }
            set
            {
                if (this._categories__status != value)
                {
                    this.IsDirty = true;
                    this._categories__status = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
