//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table categories_descriptions 
    /// </summary>
    public partial class categories_descriptionsModel 
    {
        #region Ctor

        // Default contructor
        public categories_descriptionsModel()
        {
            this.IsNewItem = true;
            this._categories__descriptions = new categories_descriptions();
        }

        // Default contructor that set entity to field
        public categories_descriptionsModel(categories_descriptions categories_descriptions)
        {
        	this._categories__descriptions = categories_descriptions;
            this._categories__id = categories_descriptions.categories_id;
            this._language__id = categories_descriptions.language_id;
            this._categories__name = categories_descriptions.categories_name;
            this._categories__description_1 = categories_descriptions.categories_description1;
            this._originalcategories_descriptions = categories_descriptions.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private categories_descriptions _categories__descriptions;
        private categories_descriptions _originalcategories_descriptions;
        
        public categories_descriptions Mapcategories_descriptions()
        {
            this._categories__descriptions.categories_id = this._categories__id;
            this._categories__descriptions.language_id = this._language__id;
            this._categories__descriptions.categories_name = this._categories__name;
            this._categories__descriptions.categories_description1 = this._categories__description_1;
        	return _categories__descriptions;
        }
        
        public void Undo()
        {
            if(this._originalcategories_descriptions == null) return;
            this._categories__id = this._originalcategories_descriptions.categories_id;
            this._language__id = this._originalcategories_descriptions.language_id;
            this._categories__name = this._originalcategories_descriptions.categories_name;
            this._categories__description_1 = this._originalcategories_descriptions.categories_description1;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalcategories_descriptions == null) return;
            this._categories__descriptions.categories_id = this._originalcategories_descriptions.categories_id;
            this._categories__descriptions.language_id = this._originalcategories_descriptions.language_id;
            this._categories__descriptions.categories_name = this._originalcategories_descriptions.categories_name;
            this._categories__descriptions.categories_description1 = this._originalcategories_descriptions.categories_description1;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _categories__id;
        public int categories_id
        {
            get { return this._categories__id; }
            set
            {
                if (this._categories__id != value)
                {
                    this.IsDirty = true;
                    this._categories__id = value;
                }
            }
        }
        
        private int _language__id;
        public int language_id
        {
            get { return this._language__id; }
            set
            {
                if (this._language__id != value)
                {
                    this.IsDirty = true;
                    this._language__id = value;
                }
            }
        }
        
        private string _categories__name;
        public string categories_name
        {
            get { return this._categories__name; }
            set
            {
                if (this._categories__name != value)
                {
                    this.IsDirty = true;
                    this._categories__name = value;
                }
            }
        }
        
        private string _categories__description_1;
        public string categories_description1
        {
            get { return this._categories__description_1; }
            set
            {
                if (this._categories__description_1 != value)
                {
                    this.IsDirty = true;
                    this._categories__description_1 = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
