//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table manufacturers_info 
    /// </summary>
    public partial class manufacturers_infoModel 
    {
        #region Ctor

        // Default contructor
        public manufacturers_infoModel()
        {
            this.IsNewItem = true;
            this._manufacturers__info = new manufacturers_info();
        }

        // Default contructor that set entity to field
        public manufacturers_infoModel(manufacturers_info manufacturers_info)
        {
        	this._manufacturers__info = manufacturers_info;
            this._manufacturers__id = manufacturers_info.manufacturers_id;
            this._languages__id = manufacturers_info.languages_id;
            this._manufacturers__url = manufacturers_info.manufacturers_url;
            this._url__clicked = manufacturers_info.url_clicked;
            this._date__last__click = manufacturers_info.date_last_click;
            this._originalmanufacturers_info = manufacturers_info.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private manufacturers_info _manufacturers__info;
        private manufacturers_info _originalmanufacturers_info;
        
        public manufacturers_info Mapmanufacturers_info()
        {
            this._manufacturers__info.manufacturers_id = this._manufacturers__id;
            this._manufacturers__info.languages_id = this._languages__id;
            this._manufacturers__info.manufacturers_url = this._manufacturers__url;
            this._manufacturers__info.url_clicked = this._url__clicked;
            this._manufacturers__info.date_last_click = this._date__last__click;
        	return _manufacturers__info;
        }
        
        public void Undo()
        {
            if(this._originalmanufacturers_info == null) return;
            this._manufacturers__id = this._originalmanufacturers_info.manufacturers_id;
            this._languages__id = this._originalmanufacturers_info.languages_id;
            this._manufacturers__url = this._originalmanufacturers_info.manufacturers_url;
            this._url__clicked = this._originalmanufacturers_info.url_clicked;
            this._date__last__click = this._originalmanufacturers_info.date_last_click;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalmanufacturers_info == null) return;
            this._manufacturers__info.manufacturers_id = this._originalmanufacturers_info.manufacturers_id;
            this._manufacturers__info.languages_id = this._originalmanufacturers_info.languages_id;
            this._manufacturers__info.manufacturers_url = this._originalmanufacturers_info.manufacturers_url;
            this._manufacturers__info.url_clicked = this._originalmanufacturers_info.url_clicked;
            this._manufacturers__info.date_last_click = this._originalmanufacturers_info.date_last_click;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _manufacturers__id;
        public int manufacturers_id
        {
            get { return this._manufacturers__id; }
            set
            {
                if (this._manufacturers__id != value)
                {
                    this.IsDirty = true;
                    this._manufacturers__id = value;
                }
            }
        }
        
        private int _languages__id;
        public int languages_id
        {
            get { return this._languages__id; }
            set
            {
                if (this._languages__id != value)
                {
                    this.IsDirty = true;
                    this._languages__id = value;
                }
            }
        }
        
        private string _manufacturers__url;
        public string manufacturers_url
        {
            get { return this._manufacturers__url; }
            set
            {
                if (this._manufacturers__url != value)
                {
                    this.IsDirty = true;
                    this._manufacturers__url = value;
                }
            }
        }
        
        private int _url__clicked;
        public int url_clicked
        {
            get { return this._url__clicked; }
            set
            {
                if (this._url__clicked != value)
                {
                    this.IsDirty = true;
                    this._url__clicked = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _date__last__click;
        public Nullable<System.DateTime> date_last_click
        {
            get { return this._date__last__click; }
            set
            {
                if (this._date__last__click != value)
                {
                    this.IsDirty = true;
                    this._date__last__click = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
