//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table orders_status 
    /// </summary>
    public partial class orders_statusModel 
    {
        #region Ctor

        // Default contructor
        public orders_statusModel()
        {
            this.IsNewItem = true;
            this._orders__status = new orders_status();
        }

        // Default contructor that set entity to field
        public orders_statusModel(orders_status orders_status)
        {
        	this._orders__status = orders_status;
            this._orders__status__id = orders_status.orders_status_id;
            this._language__id = orders_status.language_id;
            this._orders__status__name = orders_status.orders_status_name;
            this._originalorders_status = orders_status.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private orders_status _orders__status;
        private orders_status _originalorders_status;
        
        public orders_status Maporders_status()
        {
            this._orders__status.orders_status_id = this._orders__status__id;
            this._orders__status.language_id = this._language__id;
            this._orders__status.orders_status_name = this._orders__status__name;
        	return _orders__status;
        }
        
        public void Undo()
        {
            if(this._originalorders_status == null) return;
            this._orders__status__id = this._originalorders_status.orders_status_id;
            this._language__id = this._originalorders_status.language_id;
            this._orders__status__name = this._originalorders_status.orders_status_name;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalorders_status == null) return;
            this._orders__status.orders_status_id = this._originalorders_status.orders_status_id;
            this._orders__status.language_id = this._originalorders_status.language_id;
            this._orders__status.orders_status_name = this._originalorders_status.orders_status_name;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _orders__status__id;
        public int orders_status_id
        {
            get { return this._orders__status__id; }
            set
            {
                if (this._orders__status__id != value)
                {
                    this.IsDirty = true;
                    this._orders__status__id = value;
                }
            }
        }
        
        private int _language__id;
        public int language_id
        {
            get { return this._language__id; }
            set
            {
                if (this._language__id != value)
                {
                    this.IsDirty = true;
                    this._language__id = value;
                }
            }
        }
        
        private string _orders__status__name;
        public string orders_status_name
        {
            get { return this._orders__status__name; }
            set
            {
                if (this._orders__status__name != value)
                {
                    this.IsDirty = true;
                    this._orders__status__name = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
