//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table orders_products 
    /// </summary>
    public partial class orders_productsModel 
    {
        #region Ctor

        // Default contructor
        public orders_productsModel()
        {
            this.IsNewItem = true;
            this._orders__products = new orders_products();
        }

        // Default contructor that set entity to field
        public orders_productsModel(orders_products orders_products)
        {
        	this._orders__products = orders_products;
            this._orders__products__id = orders_products.orders_products_id;
            this._orders__id = orders_products.orders_id;
            this._products__id = orders_products.products_id;
            this._products__model = orders_products.products_model;
            this._products__name = orders_products.products_name;
            this._products__price = orders_products.products_price;
            this._final__price = orders_products.final_price;
            this._products__tax = orders_products.products_tax;
            this._products__quantity = orders_products.products_quantity;
            this._onetime__charges = orders_products.onetime_charges;
            this._products__priced__by__attribute = orders_products.products_priced_by_attribute;
            this._product__is__free = orders_products.product_is_free;
            this._products__discount__type = orders_products.products_discount_type;
            this._products__discount__type__from = orders_products.products_discount_type_from;
            this._products__prid = orders_products.products_prid;
            this._originalorders_products = orders_products.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private orders_products _orders__products;
        private orders_products _originalorders_products;
        
        public orders_products Maporders_products()
        {
            this._orders__products.orders_products_id = this._orders__products__id;
            this._orders__products.orders_id = this._orders__id;
            this._orders__products.products_id = this._products__id;
            this._orders__products.products_model = this._products__model;
            this._orders__products.products_name = this._products__name;
            this._orders__products.products_price = this._products__price;
            this._orders__products.final_price = this._final__price;
            this._orders__products.products_tax = this._products__tax;
            this._orders__products.products_quantity = this._products__quantity;
            this._orders__products.onetime_charges = this._onetime__charges;
            this._orders__products.products_priced_by_attribute = this._products__priced__by__attribute;
            this._orders__products.product_is_free = this._product__is__free;
            this._orders__products.products_discount_type = this._products__discount__type;
            this._orders__products.products_discount_type_from = this._products__discount__type__from;
            this._orders__products.products_prid = this._products__prid;
        	return _orders__products;
        }
        
        public void Undo()
        {
            if(this._originalorders_products == null) return;
            this._orders__products__id = this._originalorders_products.orders_products_id;
            this._orders__id = this._originalorders_products.orders_id;
            this._products__id = this._originalorders_products.products_id;
            this._products__model = this._originalorders_products.products_model;
            this._products__name = this._originalorders_products.products_name;
            this._products__price = this._originalorders_products.products_price;
            this._final__price = this._originalorders_products.final_price;
            this._products__tax = this._originalorders_products.products_tax;
            this._products__quantity = this._originalorders_products.products_quantity;
            this._onetime__charges = this._originalorders_products.onetime_charges;
            this._products__priced__by__attribute = this._originalorders_products.products_priced_by_attribute;
            this._product__is__free = this._originalorders_products.product_is_free;
            this._products__discount__type = this._originalorders_products.products_discount_type;
            this._products__discount__type__from = this._originalorders_products.products_discount_type_from;
            this._products__prid = this._originalorders_products.products_prid;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalorders_products == null) return;
            this._orders__products.orders_products_id = this._originalorders_products.orders_products_id;
            this._orders__products.orders_id = this._originalorders_products.orders_id;
            this._orders__products.products_id = this._originalorders_products.products_id;
            this._orders__products.products_model = this._originalorders_products.products_model;
            this._orders__products.products_name = this._originalorders_products.products_name;
            this._orders__products.products_price = this._originalorders_products.products_price;
            this._orders__products.final_price = this._originalorders_products.final_price;
            this._orders__products.products_tax = this._originalorders_products.products_tax;
            this._orders__products.products_quantity = this._originalorders_products.products_quantity;
            this._orders__products.onetime_charges = this._originalorders_products.onetime_charges;
            this._orders__products.products_priced_by_attribute = this._originalorders_products.products_priced_by_attribute;
            this._orders__products.product_is_free = this._originalorders_products.product_is_free;
            this._orders__products.products_discount_type = this._originalorders_products.products_discount_type;
            this._orders__products.products_discount_type_from = this._originalorders_products.products_discount_type_from;
            this._orders__products.products_prid = this._originalorders_products.products_prid;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _orders__products__id;
        public int orders_products_id
        {
            get { return this._orders__products__id; }
            set
            {
                if (this._orders__products__id != value)
                {
                    this.IsDirty = true;
                    this._orders__products__id = value;
                }
            }
        }
        
        private int _orders__id;
        public int orders_id
        {
            get { return this._orders__id; }
            set
            {
                if (this._orders__id != value)
                {
                    this.IsDirty = true;
                    this._orders__id = value;
                }
            }
        }
        
        private int _products__id;
        public int products_id
        {
            get { return this._products__id; }
            set
            {
                if (this._products__id != value)
                {
                    this.IsDirty = true;
                    this._products__id = value;
                }
            }
        }
        
        private string _products__model;
        public string products_model
        {
            get { return this._products__model; }
            set
            {
                if (this._products__model != value)
                {
                    this.IsDirty = true;
                    this._products__model = value;
                }
            }
        }
        
        private string _products__name;
        public string products_name
        {
            get { return this._products__name; }
            set
            {
                if (this._products__name != value)
                {
                    this.IsDirty = true;
                    this._products__name = value;
                }
            }
        }
        
        private decimal _products__price;
        public decimal products_price
        {
            get { return this._products__price; }
            set
            {
                if (this._products__price != value)
                {
                    this.IsDirty = true;
                    this._products__price = value;
                }
            }
        }
        
        private decimal _final__price;
        public decimal final_price
        {
            get { return this._final__price; }
            set
            {
                if (this._final__price != value)
                {
                    this.IsDirty = true;
                    this._final__price = value;
                }
            }
        }
        
        private decimal _products__tax;
        public decimal products_tax
        {
            get { return this._products__tax; }
            set
            {
                if (this._products__tax != value)
                {
                    this.IsDirty = true;
                    this._products__tax = value;
                }
            }
        }
        
        private float _products__quantity;
        public float products_quantity
        {
            get { return this._products__quantity; }
            set
            {
                if (this._products__quantity != value)
                {
                    this.IsDirty = true;
                    this._products__quantity = value;
                }
            }
        }
        
        private decimal _onetime__charges;
        public decimal onetime_charges
        {
            get { return this._onetime__charges; }
            set
            {
                if (this._onetime__charges != value)
                {
                    this.IsDirty = true;
                    this._onetime__charges = value;
                }
            }
        }
        
        private short _products__priced__by__attribute;
        public short products_priced_by_attribute
        {
            get { return this._products__priced__by__attribute; }
            set
            {
                if (this._products__priced__by__attribute != value)
                {
                    this.IsDirty = true;
                    this._products__priced__by__attribute = value;
                }
            }
        }
        
        private short _product__is__free;
        public short product_is_free
        {
            get { return this._product__is__free; }
            set
            {
                if (this._product__is__free != value)
                {
                    this.IsDirty = true;
                    this._product__is__free = value;
                }
            }
        }
        
        private short _products__discount__type;
        public short products_discount_type
        {
            get { return this._products__discount__type; }
            set
            {
                if (this._products__discount__type != value)
                {
                    this.IsDirty = true;
                    this._products__discount__type = value;
                }
            }
        }
        
        private short _products__discount__type__from;
        public short products_discount_type_from
        {
            get { return this._products__discount__type__from; }
            set
            {
                if (this._products__discount__type__from != value)
                {
                    this.IsDirty = true;
                    this._products__discount__type__from = value;
                }
            }
        }
        
        private string _products__prid;
        public string products_prid
        {
            get { return this._products__prid; }
            set
            {
                if (this._products__prid != value)
                {
                    this.IsDirty = true;
                    this._products__prid = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
