//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table products 
    /// </summary>
    public partial class productsModel 
    {
        #region Ctor

        // Default contructor
        public productsModel()
        {
            this.IsNewItem = true;
            this._products = new products();
        }

        // Default contructor that set entity to field
        public productsModel(products products)
        {
        	this._products = products;
            this._products__id = products.products_id;
            this._products__type = products.products_type;
            this._products__quantity = products.products_quantity;
            this._products__model = products.products_model;
            this._products__image = products.products_image;
            this._products__price = products.products_price;
            this._products__virtual = products.products_virtual;
            this._products__date__added = products.products_date_added;
            this._products__last__modified = products.products_last_modified;
            this._products__date__available = products.products_date_available;
            this._products__weight = products.products_weight;
            this._products__status = products.products_status;
            this._products__tax__class__id = products.products_tax_class_id;
            this._manufacturers__id = products.manufacturers_id;
            this._products__ordered = products.products_ordered;
            this._products__quantity__order__min = products.products_quantity_order_min;
            this._products__quantity__order__units = products.products_quantity_order_units;
            this._products__priced__by__attribute = products.products_priced_by_attribute;
            this._product__is__free = products.product_is_free;
            this._product__is__call = products.product_is_call;
            this._products__quantity__mixed = products.products_quantity_mixed;
            this._product__is__always__free__shipping = products.product_is_always_free_shipping;
            this._products__qty__box__status = products.products_qty_box_status;
            this._products__quantity__order__max = products.products_quantity_order_max;
            this._products__sort__order = products.products_sort_order;
            this._products__discount__type = products.products_discount_type;
            this._products__discount__type__from = products.products_discount_type_from;
            this._products__price__sorter = products.products_price_sorter;
            this._master__categories__id = products.master_categories_id;
            this._products__mixed__discount__quantity = products.products_mixed_discount_quantity;
            this._metatags__title__status = products.metatags_title_status;
            this._metatags__products__name__status = products.metatags_products_name_status;
            this._metatags__model__status = products.metatags_model_status;
            this._metatags__price__status = products.metatags_price_status;
            this._metatags__title__tagline__status = products.metatags_title_tagline_status;
            this._originalproducts = products.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private products _products;
        private products _originalproducts;
        
        public products Mapproducts()
        {
            this._products.products_id = this._products__id;
            this._products.products_type = this._products__type;
            this._products.products_quantity = this._products__quantity;
            this._products.products_model = this._products__model;
            this._products.products_image = this._products__image;
            this._products.products_price = this._products__price;
            this._products.products_virtual = this._products__virtual;
            this._products.products_date_added = this._products__date__added;
            this._products.products_last_modified = this._products__last__modified;
            this._products.products_date_available = this._products__date__available;
            this._products.products_weight = this._products__weight;
            this._products.products_status = this._products__status;
            this._products.products_tax_class_id = this._products__tax__class__id;
            this._products.manufacturers_id = this._manufacturers__id;
            this._products.products_ordered = this._products__ordered;
            this._products.products_quantity_order_min = this._products__quantity__order__min;
            this._products.products_quantity_order_units = this._products__quantity__order__units;
            this._products.products_priced_by_attribute = this._products__priced__by__attribute;
            this._products.product_is_free = this._product__is__free;
            this._products.product_is_call = this._product__is__call;
            this._products.products_quantity_mixed = this._products__quantity__mixed;
            this._products.product_is_always_free_shipping = this._product__is__always__free__shipping;
            this._products.products_qty_box_status = this._products__qty__box__status;
            this._products.products_quantity_order_max = this._products__quantity__order__max;
            this._products.products_sort_order = this._products__sort__order;
            this._products.products_discount_type = this._products__discount__type;
            this._products.products_discount_type_from = this._products__discount__type__from;
            this._products.products_price_sorter = this._products__price__sorter;
            this._products.master_categories_id = this._master__categories__id;
            this._products.products_mixed_discount_quantity = this._products__mixed__discount__quantity;
            this._products.metatags_title_status = this._metatags__title__status;
            this._products.metatags_products_name_status = this._metatags__products__name__status;
            this._products.metatags_model_status = this._metatags__model__status;
            this._products.metatags_price_status = this._metatags__price__status;
            this._products.metatags_title_tagline_status = this._metatags__title__tagline__status;
        	return _products;
        }
        
        public void Undo()
        {
            if(this._originalproducts == null) return;
            this._products__id = this._originalproducts.products_id;
            this._products__type = this._originalproducts.products_type;
            this._products__quantity = this._originalproducts.products_quantity;
            this._products__model = this._originalproducts.products_model;
            this._products__image = this._originalproducts.products_image;
            this._products__price = this._originalproducts.products_price;
            this._products__virtual = this._originalproducts.products_virtual;
            this._products__date__added = this._originalproducts.products_date_added;
            this._products__last__modified = this._originalproducts.products_last_modified;
            this._products__date__available = this._originalproducts.products_date_available;
            this._products__weight = this._originalproducts.products_weight;
            this._products__status = this._originalproducts.products_status;
            this._products__tax__class__id = this._originalproducts.products_tax_class_id;
            this._manufacturers__id = this._originalproducts.manufacturers_id;
            this._products__ordered = this._originalproducts.products_ordered;
            this._products__quantity__order__min = this._originalproducts.products_quantity_order_min;
            this._products__quantity__order__units = this._originalproducts.products_quantity_order_units;
            this._products__priced__by__attribute = this._originalproducts.products_priced_by_attribute;
            this._product__is__free = this._originalproducts.product_is_free;
            this._product__is__call = this._originalproducts.product_is_call;
            this._products__quantity__mixed = this._originalproducts.products_quantity_mixed;
            this._product__is__always__free__shipping = this._originalproducts.product_is_always_free_shipping;
            this._products__qty__box__status = this._originalproducts.products_qty_box_status;
            this._products__quantity__order__max = this._originalproducts.products_quantity_order_max;
            this._products__sort__order = this._originalproducts.products_sort_order;
            this._products__discount__type = this._originalproducts.products_discount_type;
            this._products__discount__type__from = this._originalproducts.products_discount_type_from;
            this._products__price__sorter = this._originalproducts.products_price_sorter;
            this._master__categories__id = this._originalproducts.master_categories_id;
            this._products__mixed__discount__quantity = this._originalproducts.products_mixed_discount_quantity;
            this._metatags__title__status = this._originalproducts.metatags_title_status;
            this._metatags__products__name__status = this._originalproducts.metatags_products_name_status;
            this._metatags__model__status = this._originalproducts.metatags_model_status;
            this._metatags__price__status = this._originalproducts.metatags_price_status;
            this._metatags__title__tagline__status = this._originalproducts.metatags_title_tagline_status;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalproducts == null) return;
            this._products.products_id = this._originalproducts.products_id;
            this._products.products_type = this._originalproducts.products_type;
            this._products.products_quantity = this._originalproducts.products_quantity;
            this._products.products_model = this._originalproducts.products_model;
            this._products.products_image = this._originalproducts.products_image;
            this._products.products_price = this._originalproducts.products_price;
            this._products.products_virtual = this._originalproducts.products_virtual;
            this._products.products_date_added = this._originalproducts.products_date_added;
            this._products.products_last_modified = this._originalproducts.products_last_modified;
            this._products.products_date_available = this._originalproducts.products_date_available;
            this._products.products_weight = this._originalproducts.products_weight;
            this._products.products_status = this._originalproducts.products_status;
            this._products.products_tax_class_id = this._originalproducts.products_tax_class_id;
            this._products.manufacturers_id = this._originalproducts.manufacturers_id;
            this._products.products_ordered = this._originalproducts.products_ordered;
            this._products.products_quantity_order_min = this._originalproducts.products_quantity_order_min;
            this._products.products_quantity_order_units = this._originalproducts.products_quantity_order_units;
            this._products.products_priced_by_attribute = this._originalproducts.products_priced_by_attribute;
            this._products.product_is_free = this._originalproducts.product_is_free;
            this._products.product_is_call = this._originalproducts.product_is_call;
            this._products.products_quantity_mixed = this._originalproducts.products_quantity_mixed;
            this._products.product_is_always_free_shipping = this._originalproducts.product_is_always_free_shipping;
            this._products.products_qty_box_status = this._originalproducts.products_qty_box_status;
            this._products.products_quantity_order_max = this._originalproducts.products_quantity_order_max;
            this._products.products_sort_order = this._originalproducts.products_sort_order;
            this._products.products_discount_type = this._originalproducts.products_discount_type;
            this._products.products_discount_type_from = this._originalproducts.products_discount_type_from;
            this._products.products_price_sorter = this._originalproducts.products_price_sorter;
            this._products.master_categories_id = this._originalproducts.master_categories_id;
            this._products.products_mixed_discount_quantity = this._originalproducts.products_mixed_discount_quantity;
            this._products.metatags_title_status = this._originalproducts.metatags_title_status;
            this._products.metatags_products_name_status = this._originalproducts.metatags_products_name_status;
            this._products.metatags_model_status = this._originalproducts.metatags_model_status;
            this._products.metatags_price_status = this._originalproducts.metatags_price_status;
            this._products.metatags_title_tagline_status = this._originalproducts.metatags_title_tagline_status;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _products__id;
        public int products_id
        {
            get { return this._products__id; }
            set
            {
                if (this._products__id != value)
                {
                    this.IsDirty = true;
                    this._products__id = value;
                }
            }
        }
        
        private int _products__type;
        public int products_type
        {
            get { return this._products__type; }
            set
            {
                if (this._products__type != value)
                {
                    this.IsDirty = true;
                    this._products__type = value;
                }
            }
        }
        
        private float _products__quantity;
        public float products_quantity
        {
            get { return this._products__quantity; }
            set
            {
                if (this._products__quantity != value)
                {
                    this.IsDirty = true;
                    this._products__quantity = value;
                }
            }
        }
        
        private string _products__model;
        public string products_model
        {
            get { return this._products__model; }
            set
            {
                if (this._products__model != value)
                {
                    this.IsDirty = true;
                    this._products__model = value;
                }
            }
        }
        
        private string _products__image;
        public string products_image
        {
            get { return this._products__image; }
            set
            {
                if (this._products__image != value)
                {
                    this.IsDirty = true;
                    this._products__image = value;
                }
            }
        }
        
        private decimal _products__price;
        public decimal products_price
        {
            get { return this._products__price; }
            set
            {
                if (this._products__price != value)
                {
                    this.IsDirty = true;
                    this._products__price = value;
                }
            }
        }
        
        private short _products__virtual;
        public short products_virtual
        {
            get { return this._products__virtual; }
            set
            {
                if (this._products__virtual != value)
                {
                    this.IsDirty = true;
                    this._products__virtual = value;
                }
            }
        }
        
        private System.DateTime _products__date__added;
        public System.DateTime products_date_added
        {
            get { return this._products__date__added; }
            set
            {
                if (this._products__date__added != value)
                {
                    this.IsDirty = true;
                    this._products__date__added = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _products__last__modified;
        public Nullable<System.DateTime> products_last_modified
        {
            get { return this._products__last__modified; }
            set
            {
                if (this._products__last__modified != value)
                {
                    this.IsDirty = true;
                    this._products__last__modified = value;
                }
            }
        }
        
        private Nullable<System.DateTime> _products__date__available;
        public Nullable<System.DateTime> products_date_available
        {
            get { return this._products__date__available; }
            set
            {
                if (this._products__date__available != value)
                {
                    this.IsDirty = true;
                    this._products__date__available = value;
                }
            }
        }
        
        private float _products__weight;
        public float products_weight
        {
            get { return this._products__weight; }
            set
            {
                if (this._products__weight != value)
                {
                    this.IsDirty = true;
                    this._products__weight = value;
                }
            }
        }
        
        private short _products__status;
        public short products_status
        {
            get { return this._products__status; }
            set
            {
                if (this._products__status != value)
                {
                    this.IsDirty = true;
                    this._products__status = value;
                }
            }
        }
        
        private int _products__tax__class__id;
        public int products_tax_class_id
        {
            get { return this._products__tax__class__id; }
            set
            {
                if (this._products__tax__class__id != value)
                {
                    this.IsDirty = true;
                    this._products__tax__class__id = value;
                }
            }
        }
        
        private Nullable<int> _manufacturers__id;
        public Nullable<int> manufacturers_id
        {
            get { return this._manufacturers__id; }
            set
            {
                if (this._manufacturers__id != value)
                {
                    this.IsDirty = true;
                    this._manufacturers__id = value;
                }
            }
        }
        
        private float _products__ordered;
        public float products_ordered
        {
            get { return this._products__ordered; }
            set
            {
                if (this._products__ordered != value)
                {
                    this.IsDirty = true;
                    this._products__ordered = value;
                }
            }
        }
        
        private float _products__quantity__order__min;
        public float products_quantity_order_min
        {
            get { return this._products__quantity__order__min; }
            set
            {
                if (this._products__quantity__order__min != value)
                {
                    this.IsDirty = true;
                    this._products__quantity__order__min = value;
                }
            }
        }
        
        private float _products__quantity__order__units;
        public float products_quantity_order_units
        {
            get { return this._products__quantity__order__units; }
            set
            {
                if (this._products__quantity__order__units != value)
                {
                    this.IsDirty = true;
                    this._products__quantity__order__units = value;
                }
            }
        }
        
        private short _products__priced__by__attribute;
        public short products_priced_by_attribute
        {
            get { return this._products__priced__by__attribute; }
            set
            {
                if (this._products__priced__by__attribute != value)
                {
                    this.IsDirty = true;
                    this._products__priced__by__attribute = value;
                }
            }
        }
        
        private short _product__is__free;
        public short product_is_free
        {
            get { return this._product__is__free; }
            set
            {
                if (this._product__is__free != value)
                {
                    this.IsDirty = true;
                    this._product__is__free = value;
                }
            }
        }
        
        private short _product__is__call;
        public short product_is_call
        {
            get { return this._product__is__call; }
            set
            {
                if (this._product__is__call != value)
                {
                    this.IsDirty = true;
                    this._product__is__call = value;
                }
            }
        }
        
        private short _products__quantity__mixed;
        public short products_quantity_mixed
        {
            get { return this._products__quantity__mixed; }
            set
            {
                if (this._products__quantity__mixed != value)
                {
                    this.IsDirty = true;
                    this._products__quantity__mixed = value;
                }
            }
        }
        
        private short _product__is__always__free__shipping;
        public short product_is_always_free_shipping
        {
            get { return this._product__is__always__free__shipping; }
            set
            {
                if (this._product__is__always__free__shipping != value)
                {
                    this.IsDirty = true;
                    this._product__is__always__free__shipping = value;
                }
            }
        }
        
        private short _products__qty__box__status;
        public short products_qty_box_status
        {
            get { return this._products__qty__box__status; }
            set
            {
                if (this._products__qty__box__status != value)
                {
                    this.IsDirty = true;
                    this._products__qty__box__status = value;
                }
            }
        }
        
        private float _products__quantity__order__max;
        public float products_quantity_order_max
        {
            get { return this._products__quantity__order__max; }
            set
            {
                if (this._products__quantity__order__max != value)
                {
                    this.IsDirty = true;
                    this._products__quantity__order__max = value;
                }
            }
        }
        
        private int _products__sort__order;
        public int products_sort_order
        {
            get { return this._products__sort__order; }
            set
            {
                if (this._products__sort__order != value)
                {
                    this.IsDirty = true;
                    this._products__sort__order = value;
                }
            }
        }
        
        private short _products__discount__type;
        public short products_discount_type
        {
            get { return this._products__discount__type; }
            set
            {
                if (this._products__discount__type != value)
                {
                    this.IsDirty = true;
                    this._products__discount__type = value;
                }
            }
        }
        
        private short _products__discount__type__from;
        public short products_discount_type_from
        {
            get { return this._products__discount__type__from; }
            set
            {
                if (this._products__discount__type__from != value)
                {
                    this.IsDirty = true;
                    this._products__discount__type__from = value;
                }
            }
        }
        
        private decimal _products__price__sorter;
        public decimal products_price_sorter
        {
            get { return this._products__price__sorter; }
            set
            {
                if (this._products__price__sorter != value)
                {
                    this.IsDirty = true;
                    this._products__price__sorter = value;
                }
            }
        }
        
        private int _master__categories__id;
        public int master_categories_id
        {
            get { return this._master__categories__id; }
            set
            {
                if (this._master__categories__id != value)
                {
                    this.IsDirty = true;
                    this._master__categories__id = value;
                }
            }
        }
        
        private short _products__mixed__discount__quantity;
        public short products_mixed_discount_quantity
        {
            get { return this._products__mixed__discount__quantity; }
            set
            {
                if (this._products__mixed__discount__quantity != value)
                {
                    this.IsDirty = true;
                    this._products__mixed__discount__quantity = value;
                }
            }
        }
        
        private short _metatags__title__status;
        public short metatags_title_status
        {
            get { return this._metatags__title__status; }
            set
            {
                if (this._metatags__title__status != value)
                {
                    this.IsDirty = true;
                    this._metatags__title__status = value;
                }
            }
        }
        
        private short _metatags__products__name__status;
        public short metatags_products_name_status
        {
            get { return this._metatags__products__name__status; }
            set
            {
                if (this._metatags__products__name__status != value)
                {
                    this.IsDirty = true;
                    this._metatags__products__name__status = value;
                }
            }
        }
        
        private short _metatags__model__status;
        public short metatags_model_status
        {
            get { return this._metatags__model__status; }
            set
            {
                if (this._metatags__model__status != value)
                {
                    this.IsDirty = true;
                    this._metatags__model__status = value;
                }
            }
        }
        
        private short _metatags__price__status;
        public short metatags_price_status
        {
            get { return this._metatags__price__status; }
            set
            {
                if (this._metatags__price__status != value)
                {
                    this.IsDirty = true;
                    this._metatags__price__status = value;
                }
            }
        }
        
        private short _metatags__title__tagline__status;
        public short metatags_title_tagline_status
        {
            get { return this._metatags__title__tagline__status; }
            set
            {
                if (this._metatags__title__tagline__status != value)
                {
                    this.IsDirty = true;
                    this._metatags__title__tagline__status = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
