//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace phukienipadx.Dal.Models
{
    /// <summary>
    /// Model for table products_descriptions 
    /// </summary>
    public partial class products_descriptionsModel 
    {
        #region Ctor

        // Default contructor
        public products_descriptionsModel()
        {
            this.IsNewItem = true;
            this._products__descriptions = new products_descriptions();
        }

        // Default contructor that set entity to field
        public products_descriptionsModel(products_descriptions products_descriptions)
        {
        	this._products__descriptions = products_descriptions;
            this._products__id = products_descriptions.products_id;
            this._language__id = products_descriptions.language_id;
            this._products__name = products_descriptions.products_name;
            this._products__images = products_descriptions.products_images;
            this._products__description_1 = products_descriptions.products_description1;
            this._products__url = products_descriptions.products_url;
            this._products__viewed = products_descriptions.products_viewed;
            this._originalproducts_descriptions = products_descriptions.DeepClone();
        }

        #endregion

        #region Entity Properties

        
        public event EventHandler PropertyChanged;
        private products_descriptions _products__descriptions;
        private products_descriptions _originalproducts_descriptions;
        
        public products_descriptions Mapproducts_descriptions()
        {
            this._products__descriptions.products_id = this._products__id;
            this._products__descriptions.language_id = this._language__id;
            this._products__descriptions.products_name = this._products__name;
            this._products__descriptions.products_images = this._products__images;
            this._products__descriptions.products_description1 = this._products__description_1;
            this._products__descriptions.products_url = this._products__url;
            this._products__descriptions.products_viewed = this._products__viewed;
        	return _products__descriptions;
        }
        
        public void Undo()
        {
            if(this._originalproducts_descriptions == null) return;
            this._products__id = this._originalproducts_descriptions.products_id;
            this._language__id = this._originalproducts_descriptions.language_id;
            this._products__name = this._originalproducts_descriptions.products_name;
            this._products__images = this._originalproducts_descriptions.products_images;
            this._products__description_1 = this._originalproducts_descriptions.products_description1;
            this._products__url = this._originalproducts_descriptions.products_url;
            this._products__viewed = this._originalproducts_descriptions.products_viewed;
        	this.Commit();
        }
        
        public void Reload()
        {
        	if(this._originalproducts_descriptions == null) return;
            this._products__descriptions.products_id = this._originalproducts_descriptions.products_id;
            this._products__descriptions.language_id = this._originalproducts_descriptions.language_id;
            this._products__descriptions.products_name = this._originalproducts_descriptions.products_name;
            this._products__descriptions.products_images = this._originalproducts_descriptions.products_images;
            this._products__descriptions.products_description1 = this._originalproducts_descriptions.products_description1;
            this._products__descriptions.products_url = this._originalproducts_descriptions.products_url;
            this._products__descriptions.products_viewed = this._originalproducts_descriptions.products_viewed;
        }
        

        public bool IsNewItem { get; private set; }
        public bool IsDeleted { get; set; }
        public bool IsChecked { get; set; }
        
        private bool _isDirty;
        public bool IsDirty
        {
            get
            {
                return _isDirty;
            }
            private set
            {
                if (_isDirty != value)
                {
                    _isDirty = value;
                    if (PropertyChanged != null)
                        PropertyChanged.Invoke(this, new EventArgs());
                }
            }
        }
        
        public void Commit() {
        	IsNewItem = false;
        	IsDirty = false;
        }

        #endregion

        #region Primitive Properties

        
        private int _products__id;
        public int products_id
        {
            get { return this._products__id; }
            set
            {
                if (this._products__id != value)
                {
                    this.IsDirty = true;
                    this._products__id = value;
                }
            }
        }
        
        private int _language__id;
        public int language_id
        {
            get { return this._language__id; }
            set
            {
                if (this._language__id != value)
                {
                    this.IsDirty = true;
                    this._language__id = value;
                }
            }
        }
        
        private string _products__name;
        public string products_name
        {
            get { return this._products__name; }
            set
            {
                if (this._products__name != value)
                {
                    this.IsDirty = true;
                    this._products__name = value;
                }
            }
        }
        
        private string _products__images;
        public string products_images
        {
            get { return this._products__images; }
            set
            {
                if (this._products__images != value)
                {
                    this.IsDirty = true;
                    this._products__images = value;
                }
            }
        }
        
        private string _products__description_1;
        public string products_description1
        {
            get { return this._products__description_1; }
            set
            {
                if (this._products__description_1 != value)
                {
                    this.IsDirty = true;
                    this._products__description_1 = value;
                }
            }
        }
        
        private string _products__url;
        public string products_url
        {
            get { return this._products__url; }
            set
            {
                if (this._products__url != value)
                {
                    this.IsDirty = true;
                    this._products__url = value;
                }
            }
        }
        
        private Nullable<int> _products__viewed;
        public Nullable<int> products_viewed
        {
            get { return this._products__viewed; }
            set
            {
                if (this._products__viewed != value)
                {
                    this.IsDirty = true;
                    this._products__viewed = value;
                }
            }
        }

        #endregion

        #region all the custom code


        #endregion
    }
}
