#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phukienipadx.Dal
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="phu4ba65_ipadx")]
	public partial class phukienipadxDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    partial void Insertproducts_description(products_description instance);
    partial void Updateproducts_description(products_description instance);
    partial void Deleteproducts_description(products_description instance);
    partial void Insertproducts_to_category(products_to_category instance);
    partial void Updateproducts_to_category(products_to_category instance);
    partial void Deleteproducts_to_category(products_to_category instance);
    partial void Insertcategories_description(categories_description instance);
    partial void Updatecategories_description(categories_description instance);
    partial void Deletecategories_description(categories_description instance);
    partial void Insertezpage(ezpage instance);
    partial void Updateezpage(ezpage instance);
    partial void Deleteezpage(ezpage instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    #endregion
		
		public phukienipadxDataContext() : 
				base(global::phukienipadx.Dal.Properties.Settings.Default.phu4ba65_ipadxConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public phukienipadxDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public phukienipadxDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public phukienipadxDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public phukienipadxDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<products_description> products_descriptions
		{
			get
			{
				return this.GetTable<products_description>();
			}
		}
		
		public System.Data.Linq.Table<products_to_category> products_to_categories
		{
			get
			{
				return this.GetTable<products_to_category>();
			}
		}
		
		public System.Data.Linq.Table<categories_description> categories_descriptions
		{
			get
			{
				return this.GetTable<categories_description>();
			}
		}
		
		public System.Data.Linq.Table<ezpage> ezpages
		{
			get
			{
				return this.GetTable<ezpage>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _products_id;
		
		private int _products_type;
		
		private float _products_quantity;
		
		private string _products_model;
		
		private string _products_image;
		
		private decimal _products_price;
		
		private short _products_virtual;
		
		private System.DateTime _products_date_added;
		
		private System.Nullable<System.DateTime> _products_last_modified;
		
		private System.Nullable<System.DateTime> _products_date_available;
		
		private float _products_weight;
		
		private short _products_status;
		
		private int _products_tax_class_id;
		
		private System.Nullable<int> _manufacturers_id;
		
		private float _products_ordered;
		
		private float _products_quantity_order_min;
		
		private float _products_quantity_order_units;
		
		private short _products_priced_by_attribute;
		
		private short _product_is_free;
		
		private short _product_is_call;
		
		private short _products_quantity_mixed;
		
		private short _product_is_always_free_shipping;
		
		private short _products_qty_box_status;
		
		private float _products_quantity_order_max;
		
		private int _products_sort_order;
		
		private short _products_discount_type;
		
		private short _products_discount_type_from;
		
		private decimal _products_price_sorter;
		
		private int _master_categories_id;
		
		private short _products_mixed_discount_quantity;
		
		private short _metatags_title_status;
		
		private short _metatags_products_name_status;
		
		private short _metatags_model_status;
		
		private short _metatags_price_status;
		
		private short _metatags_title_tagline_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproducts_idChanging(int value);
    partial void Onproducts_idChanged();
    partial void Onproducts_typeChanging(int value);
    partial void Onproducts_typeChanged();
    partial void Onproducts_quantityChanging(float value);
    partial void Onproducts_quantityChanged();
    partial void Onproducts_modelChanging(string value);
    partial void Onproducts_modelChanged();
    partial void Onproducts_imageChanging(string value);
    partial void Onproducts_imageChanged();
    partial void Onproducts_priceChanging(decimal value);
    partial void Onproducts_priceChanged();
    partial void Onproducts_virtualChanging(short value);
    partial void Onproducts_virtualChanged();
    partial void Onproducts_date_addedChanging(System.DateTime value);
    partial void Onproducts_date_addedChanged();
    partial void Onproducts_last_modifiedChanging(System.Nullable<System.DateTime> value);
    partial void Onproducts_last_modifiedChanged();
    partial void Onproducts_date_availableChanging(System.Nullable<System.DateTime> value);
    partial void Onproducts_date_availableChanged();
    partial void Onproducts_weightChanging(float value);
    partial void Onproducts_weightChanged();
    partial void Onproducts_statusChanging(short value);
    partial void Onproducts_statusChanged();
    partial void Onproducts_tax_class_idChanging(int value);
    partial void Onproducts_tax_class_idChanged();
    partial void Onmanufacturers_idChanging(System.Nullable<int> value);
    partial void Onmanufacturers_idChanged();
    partial void Onproducts_orderedChanging(float value);
    partial void Onproducts_orderedChanged();
    partial void Onproducts_quantity_order_minChanging(float value);
    partial void Onproducts_quantity_order_minChanged();
    partial void Onproducts_quantity_order_unitsChanging(float value);
    partial void Onproducts_quantity_order_unitsChanged();
    partial void Onproducts_priced_by_attributeChanging(short value);
    partial void Onproducts_priced_by_attributeChanged();
    partial void Onproduct_is_freeChanging(short value);
    partial void Onproduct_is_freeChanged();
    partial void Onproduct_is_callChanging(short value);
    partial void Onproduct_is_callChanged();
    partial void Onproducts_quantity_mixedChanging(short value);
    partial void Onproducts_quantity_mixedChanged();
    partial void Onproduct_is_always_free_shippingChanging(short value);
    partial void Onproduct_is_always_free_shippingChanged();
    partial void Onproducts_qty_box_statusChanging(short value);
    partial void Onproducts_qty_box_statusChanged();
    partial void Onproducts_quantity_order_maxChanging(float value);
    partial void Onproducts_quantity_order_maxChanged();
    partial void Onproducts_sort_orderChanging(int value);
    partial void Onproducts_sort_orderChanged();
    partial void Onproducts_discount_typeChanging(short value);
    partial void Onproducts_discount_typeChanged();
    partial void Onproducts_discount_type_fromChanging(short value);
    partial void Onproducts_discount_type_fromChanged();
    partial void Onproducts_price_sorterChanging(decimal value);
    partial void Onproducts_price_sorterChanged();
    partial void Onmaster_categories_idChanging(int value);
    partial void Onmaster_categories_idChanged();
    partial void Onproducts_mixed_discount_quantityChanging(short value);
    partial void Onproducts_mixed_discount_quantityChanged();
    partial void Onmetatags_title_statusChanging(short value);
    partial void Onmetatags_title_statusChanged();
    partial void Onmetatags_products_name_statusChanging(short value);
    partial void Onmetatags_products_name_statusChanged();
    partial void Onmetatags_model_statusChanging(short value);
    partial void Onmetatags_model_statusChanged();
    partial void Onmetatags_price_statusChanging(short value);
    partial void Onmetatags_price_statusChanged();
    partial void Onmetatags_title_tagline_statusChanging(short value);
    partial void Onmetatags_title_tagline_statusChanged();
    #endregion
		
		public product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int products_id
		{
			get
			{
				return this._products_id;
			}
			set
			{
				if ((this._products_id != value))
				{
					this.Onproducts_idChanging(value);
					this.SendPropertyChanging();
					this._products_id = value;
					this.SendPropertyChanged("products_id");
					this.Onproducts_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_type", DbType="Int NOT NULL")]
		public int products_type
		{
			get
			{
				return this._products_type;
			}
			set
			{
				if ((this._products_type != value))
				{
					this.Onproducts_typeChanging(value);
					this.SendPropertyChanging();
					this._products_type = value;
					this.SendPropertyChanged("products_type");
					this.Onproducts_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_quantity", DbType="Real NOT NULL")]
		public float products_quantity
		{
			get
			{
				return this._products_quantity;
			}
			set
			{
				if ((this._products_quantity != value))
				{
					this.Onproducts_quantityChanging(value);
					this.SendPropertyChanging();
					this._products_quantity = value;
					this.SendPropertyChanged("products_quantity");
					this.Onproducts_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_model", DbType="NVarChar(32)")]
		public string products_model
		{
			get
			{
				return this._products_model;
			}
			set
			{
				if ((this._products_model != value))
				{
					this.Onproducts_modelChanging(value);
					this.SendPropertyChanging();
					this._products_model = value;
					this.SendPropertyChanged("products_model");
					this.Onproducts_modelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_image", DbType="NVarChar(64)")]
		public string products_image
		{
			get
			{
				return this._products_image;
			}
			set
			{
				if ((this._products_image != value))
				{
					this.Onproducts_imageChanging(value);
					this.SendPropertyChanging();
					this._products_image = value;
					this.SendPropertyChanged("products_image");
					this.Onproducts_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_price", DbType="Decimal(15,4) NOT NULL")]
		public decimal products_price
		{
			get
			{
				return this._products_price;
			}
			set
			{
				if ((this._products_price != value))
				{
					this.Onproducts_priceChanging(value);
					this.SendPropertyChanging();
					this._products_price = value;
					this.SendPropertyChanged("products_price");
					this.Onproducts_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_virtual", DbType="SmallInt NOT NULL")]
		public short products_virtual
		{
			get
			{
				return this._products_virtual;
			}
			set
			{
				if ((this._products_virtual != value))
				{
					this.Onproducts_virtualChanging(value);
					this.SendPropertyChanging();
					this._products_virtual = value;
					this.SendPropertyChanged("products_virtual");
					this.Onproducts_virtualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_date_added", DbType="DateTime2 NOT NULL")]
		public System.DateTime products_date_added
		{
			get
			{
				return this._products_date_added;
			}
			set
			{
				if ((this._products_date_added != value))
				{
					this.Onproducts_date_addedChanging(value);
					this.SendPropertyChanging();
					this._products_date_added = value;
					this.SendPropertyChanged("products_date_added");
					this.Onproducts_date_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_last_modified", DbType="DateTime2")]
		public System.Nullable<System.DateTime> products_last_modified
		{
			get
			{
				return this._products_last_modified;
			}
			set
			{
				if ((this._products_last_modified != value))
				{
					this.Onproducts_last_modifiedChanging(value);
					this.SendPropertyChanging();
					this._products_last_modified = value;
					this.SendPropertyChanged("products_last_modified");
					this.Onproducts_last_modifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_date_available", DbType="DateTime2")]
		public System.Nullable<System.DateTime> products_date_available
		{
			get
			{
				return this._products_date_available;
			}
			set
			{
				if ((this._products_date_available != value))
				{
					this.Onproducts_date_availableChanging(value);
					this.SendPropertyChanging();
					this._products_date_available = value;
					this.SendPropertyChanged("products_date_available");
					this.Onproducts_date_availableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_weight", DbType="Real NOT NULL")]
		public float products_weight
		{
			get
			{
				return this._products_weight;
			}
			set
			{
				if ((this._products_weight != value))
				{
					this.Onproducts_weightChanging(value);
					this.SendPropertyChanging();
					this._products_weight = value;
					this.SendPropertyChanged("products_weight");
					this.Onproducts_weightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_status", DbType="SmallInt NOT NULL")]
		public short products_status
		{
			get
			{
				return this._products_status;
			}
			set
			{
				if ((this._products_status != value))
				{
					this.Onproducts_statusChanging(value);
					this.SendPropertyChanging();
					this._products_status = value;
					this.SendPropertyChanged("products_status");
					this.Onproducts_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_tax_class_id", DbType="Int NOT NULL")]
		public int products_tax_class_id
		{
			get
			{
				return this._products_tax_class_id;
			}
			set
			{
				if ((this._products_tax_class_id != value))
				{
					this.Onproducts_tax_class_idChanging(value);
					this.SendPropertyChanging();
					this._products_tax_class_id = value;
					this.SendPropertyChanged("products_tax_class_id");
					this.Onproducts_tax_class_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufacturers_id", DbType="Int")]
		public System.Nullable<int> manufacturers_id
		{
			get
			{
				return this._manufacturers_id;
			}
			set
			{
				if ((this._manufacturers_id != value))
				{
					this.Onmanufacturers_idChanging(value);
					this.SendPropertyChanging();
					this._manufacturers_id = value;
					this.SendPropertyChanged("manufacturers_id");
					this.Onmanufacturers_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_ordered", DbType="Real NOT NULL")]
		public float products_ordered
		{
			get
			{
				return this._products_ordered;
			}
			set
			{
				if ((this._products_ordered != value))
				{
					this.Onproducts_orderedChanging(value);
					this.SendPropertyChanging();
					this._products_ordered = value;
					this.SendPropertyChanged("products_ordered");
					this.Onproducts_orderedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_quantity_order_min", DbType="Real NOT NULL")]
		public float products_quantity_order_min
		{
			get
			{
				return this._products_quantity_order_min;
			}
			set
			{
				if ((this._products_quantity_order_min != value))
				{
					this.Onproducts_quantity_order_minChanging(value);
					this.SendPropertyChanging();
					this._products_quantity_order_min = value;
					this.SendPropertyChanged("products_quantity_order_min");
					this.Onproducts_quantity_order_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_quantity_order_units", DbType="Real NOT NULL")]
		public float products_quantity_order_units
		{
			get
			{
				return this._products_quantity_order_units;
			}
			set
			{
				if ((this._products_quantity_order_units != value))
				{
					this.Onproducts_quantity_order_unitsChanging(value);
					this.SendPropertyChanging();
					this._products_quantity_order_units = value;
					this.SendPropertyChanged("products_quantity_order_units");
					this.Onproducts_quantity_order_unitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_priced_by_attribute", DbType="SmallInt NOT NULL")]
		public short products_priced_by_attribute
		{
			get
			{
				return this._products_priced_by_attribute;
			}
			set
			{
				if ((this._products_priced_by_attribute != value))
				{
					this.Onproducts_priced_by_attributeChanging(value);
					this.SendPropertyChanging();
					this._products_priced_by_attribute = value;
					this.SendPropertyChanged("products_priced_by_attribute");
					this.Onproducts_priced_by_attributeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_is_free", DbType="SmallInt NOT NULL")]
		public short product_is_free
		{
			get
			{
				return this._product_is_free;
			}
			set
			{
				if ((this._product_is_free != value))
				{
					this.Onproduct_is_freeChanging(value);
					this.SendPropertyChanging();
					this._product_is_free = value;
					this.SendPropertyChanged("product_is_free");
					this.Onproduct_is_freeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_is_call", DbType="SmallInt NOT NULL")]
		public short product_is_call
		{
			get
			{
				return this._product_is_call;
			}
			set
			{
				if ((this._product_is_call != value))
				{
					this.Onproduct_is_callChanging(value);
					this.SendPropertyChanging();
					this._product_is_call = value;
					this.SendPropertyChanged("product_is_call");
					this.Onproduct_is_callChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_quantity_mixed", DbType="SmallInt NOT NULL")]
		public short products_quantity_mixed
		{
			get
			{
				return this._products_quantity_mixed;
			}
			set
			{
				if ((this._products_quantity_mixed != value))
				{
					this.Onproducts_quantity_mixedChanging(value);
					this.SendPropertyChanging();
					this._products_quantity_mixed = value;
					this.SendPropertyChanged("products_quantity_mixed");
					this.Onproducts_quantity_mixedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_is_always_free_shipping", DbType="SmallInt NOT NULL")]
		public short product_is_always_free_shipping
		{
			get
			{
				return this._product_is_always_free_shipping;
			}
			set
			{
				if ((this._product_is_always_free_shipping != value))
				{
					this.Onproduct_is_always_free_shippingChanging(value);
					this.SendPropertyChanging();
					this._product_is_always_free_shipping = value;
					this.SendPropertyChanged("product_is_always_free_shipping");
					this.Onproduct_is_always_free_shippingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_qty_box_status", DbType="SmallInt NOT NULL")]
		public short products_qty_box_status
		{
			get
			{
				return this._products_qty_box_status;
			}
			set
			{
				if ((this._products_qty_box_status != value))
				{
					this.Onproducts_qty_box_statusChanging(value);
					this.SendPropertyChanging();
					this._products_qty_box_status = value;
					this.SendPropertyChanged("products_qty_box_status");
					this.Onproducts_qty_box_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_quantity_order_max", DbType="Real NOT NULL")]
		public float products_quantity_order_max
		{
			get
			{
				return this._products_quantity_order_max;
			}
			set
			{
				if ((this._products_quantity_order_max != value))
				{
					this.Onproducts_quantity_order_maxChanging(value);
					this.SendPropertyChanging();
					this._products_quantity_order_max = value;
					this.SendPropertyChanged("products_quantity_order_max");
					this.Onproducts_quantity_order_maxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_sort_order", DbType="Int NOT NULL")]
		public int products_sort_order
		{
			get
			{
				return this._products_sort_order;
			}
			set
			{
				if ((this._products_sort_order != value))
				{
					this.Onproducts_sort_orderChanging(value);
					this.SendPropertyChanging();
					this._products_sort_order = value;
					this.SendPropertyChanged("products_sort_order");
					this.Onproducts_sort_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_discount_type", DbType="SmallInt NOT NULL")]
		public short products_discount_type
		{
			get
			{
				return this._products_discount_type;
			}
			set
			{
				if ((this._products_discount_type != value))
				{
					this.Onproducts_discount_typeChanging(value);
					this.SendPropertyChanging();
					this._products_discount_type = value;
					this.SendPropertyChanged("products_discount_type");
					this.Onproducts_discount_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_discount_type_from", DbType="SmallInt NOT NULL")]
		public short products_discount_type_from
		{
			get
			{
				return this._products_discount_type_from;
			}
			set
			{
				if ((this._products_discount_type_from != value))
				{
					this.Onproducts_discount_type_fromChanging(value);
					this.SendPropertyChanging();
					this._products_discount_type_from = value;
					this.SendPropertyChanged("products_discount_type_from");
					this.Onproducts_discount_type_fromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_price_sorter", DbType="Decimal(15,4) NOT NULL")]
		public decimal products_price_sorter
		{
			get
			{
				return this._products_price_sorter;
			}
			set
			{
				if ((this._products_price_sorter != value))
				{
					this.Onproducts_price_sorterChanging(value);
					this.SendPropertyChanging();
					this._products_price_sorter = value;
					this.SendPropertyChanged("products_price_sorter");
					this.Onproducts_price_sorterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_master_categories_id", DbType="Int NOT NULL")]
		public int master_categories_id
		{
			get
			{
				return this._master_categories_id;
			}
			set
			{
				if ((this._master_categories_id != value))
				{
					this.Onmaster_categories_idChanging(value);
					this.SendPropertyChanging();
					this._master_categories_id = value;
					this.SendPropertyChanged("master_categories_id");
					this.Onmaster_categories_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_mixed_discount_quantity", DbType="SmallInt NOT NULL")]
		public short products_mixed_discount_quantity
		{
			get
			{
				return this._products_mixed_discount_quantity;
			}
			set
			{
				if ((this._products_mixed_discount_quantity != value))
				{
					this.Onproducts_mixed_discount_quantityChanging(value);
					this.SendPropertyChanging();
					this._products_mixed_discount_quantity = value;
					this.SendPropertyChanged("products_mixed_discount_quantity");
					this.Onproducts_mixed_discount_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metatags_title_status", DbType="SmallInt NOT NULL")]
		public short metatags_title_status
		{
			get
			{
				return this._metatags_title_status;
			}
			set
			{
				if ((this._metatags_title_status != value))
				{
					this.Onmetatags_title_statusChanging(value);
					this.SendPropertyChanging();
					this._metatags_title_status = value;
					this.SendPropertyChanged("metatags_title_status");
					this.Onmetatags_title_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metatags_products_name_status", DbType="SmallInt NOT NULL")]
		public short metatags_products_name_status
		{
			get
			{
				return this._metatags_products_name_status;
			}
			set
			{
				if ((this._metatags_products_name_status != value))
				{
					this.Onmetatags_products_name_statusChanging(value);
					this.SendPropertyChanging();
					this._metatags_products_name_status = value;
					this.SendPropertyChanged("metatags_products_name_status");
					this.Onmetatags_products_name_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metatags_model_status", DbType="SmallInt NOT NULL")]
		public short metatags_model_status
		{
			get
			{
				return this._metatags_model_status;
			}
			set
			{
				if ((this._metatags_model_status != value))
				{
					this.Onmetatags_model_statusChanging(value);
					this.SendPropertyChanging();
					this._metatags_model_status = value;
					this.SendPropertyChanged("metatags_model_status");
					this.Onmetatags_model_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metatags_price_status", DbType="SmallInt NOT NULL")]
		public short metatags_price_status
		{
			get
			{
				return this._metatags_price_status;
			}
			set
			{
				if ((this._metatags_price_status != value))
				{
					this.Onmetatags_price_statusChanging(value);
					this.SendPropertyChanging();
					this._metatags_price_status = value;
					this.SendPropertyChanged("metatags_price_status");
					this.Onmetatags_price_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metatags_title_tagline_status", DbType="SmallInt NOT NULL")]
		public short metatags_title_tagline_status
		{
			get
			{
				return this._metatags_title_tagline_status;
			}
			set
			{
				if ((this._metatags_title_tagline_status != value))
				{
					this.Onmetatags_title_tagline_statusChanging(value);
					this.SendPropertyChanging();
					this._metatags_title_tagline_status = value;
					this.SendPropertyChanged("metatags_title_tagline_status");
					this.Onmetatags_title_tagline_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products_description")]
	public partial class products_description : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _products_id;
		
		private int _language_id;
		
		private string _products_name;
		
		private string _products_images;
		
		private string _products_description1;
		
		private string _products_url;
		
		private System.Nullable<int> _products_viewed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproducts_idChanging(int value);
    partial void Onproducts_idChanged();
    partial void Onlanguage_idChanging(int value);
    partial void Onlanguage_idChanged();
    partial void Onproducts_nameChanging(string value);
    partial void Onproducts_nameChanged();
    partial void Onproducts_imagesChanging(string value);
    partial void Onproducts_imagesChanged();
    partial void Onproducts_description1Changing(string value);
    partial void Onproducts_description1Changed();
    partial void Onproducts_urlChanging(string value);
    partial void Onproducts_urlChanged();
    partial void Onproducts_viewedChanging(System.Nullable<int> value);
    partial void Onproducts_viewedChanged();
    #endregion
		
		public products_description()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int products_id
		{
			get
			{
				return this._products_id;
			}
			set
			{
				if ((this._products_id != value))
				{
					this.Onproducts_idChanging(value);
					this.SendPropertyChanging();
					this._products_id = value;
					this.SendPropertyChanged("products_id");
					this.Onproducts_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int language_id
		{
			get
			{
				return this._language_id;
			}
			set
			{
				if ((this._language_id != value))
				{
					this.Onlanguage_idChanging(value);
					this.SendPropertyChanging();
					this._language_id = value;
					this.SendPropertyChanged("language_id");
					this.Onlanguage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string products_name
		{
			get
			{
				return this._products_name;
			}
			set
			{
				if ((this._products_name != value))
				{
					this.Onproducts_nameChanging(value);
					this.SendPropertyChanging();
					this._products_name = value;
					this.SendPropertyChanged("products_name");
					this.Onproducts_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_images", DbType="NVarChar(MAX)")]
		public string products_images
		{
			get
			{
				return this._products_images;
			}
			set
			{
				if ((this._products_images != value))
				{
					this.Onproducts_imagesChanging(value);
					this.SendPropertyChanging();
					this._products_images = value;
					this.SendPropertyChanged("products_images");
					this.Onproducts_imagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="products_description", Storage="_products_description1", DbType="NVarChar(MAX)")]
		public string products_description1
		{
			get
			{
				return this._products_description1;
			}
			set
			{
				if ((this._products_description1 != value))
				{
					this.Onproducts_description1Changing(value);
					this.SendPropertyChanging();
					this._products_description1 = value;
					this.SendPropertyChanged("products_description1");
					this.Onproducts_description1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_url", DbType="NVarChar(255)")]
		public string products_url
		{
			get
			{
				return this._products_url;
			}
			set
			{
				if ((this._products_url != value))
				{
					this.Onproducts_urlChanging(value);
					this.SendPropertyChanging();
					this._products_url = value;
					this.SendPropertyChanged("products_url");
					this.Onproducts_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_viewed", DbType="Int")]
		public System.Nullable<int> products_viewed
		{
			get
			{
				return this._products_viewed;
			}
			set
			{
				if ((this._products_viewed != value))
				{
					this.Onproducts_viewedChanging(value);
					this.SendPropertyChanging();
					this._products_viewed = value;
					this.SendPropertyChanged("products_viewed");
					this.Onproducts_viewedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products_to_categories")]
	public partial class products_to_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _products_id;
		
		private int _categories_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproducts_idChanging(int value);
    partial void Onproducts_idChanged();
    partial void Oncategories_idChanging(int value);
    partial void Oncategories_idChanged();
    #endregion
		
		public products_to_category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_products_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int products_id
		{
			get
			{
				return this._products_id;
			}
			set
			{
				if ((this._products_id != value))
				{
					this.Onproducts_idChanging(value);
					this.SendPropertyChanging();
					this._products_id = value;
					this.SendPropertyChanged("products_id");
					this.Onproducts_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int categories_id
		{
			get
			{
				return this._categories_id;
			}
			set
			{
				if ((this._categories_id != value))
				{
					this.Oncategories_idChanging(value);
					this.SendPropertyChanging();
					this._categories_id = value;
					this.SendPropertyChanged("categories_id");
					this.Oncategories_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categories_description")]
	public partial class categories_description : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _categories_id;
		
		private int _language_id;
		
		private string _categories_name;
		
		private string _categories_description1;
		
		private string _categories_url;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategories_idChanging(int value);
    partial void Oncategories_idChanged();
    partial void Onlanguage_idChanging(int value);
    partial void Onlanguage_idChanged();
    partial void Oncategories_nameChanging(string value);
    partial void Oncategories_nameChanged();
    partial void Oncategories_description1Changing(string value);
    partial void Oncategories_description1Changed();
    partial void Oncategories_urlChanging(string value);
    partial void Oncategories_urlChanged();
    #endregion
		
		public categories_description()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int categories_id
		{
			get
			{
				return this._categories_id;
			}
			set
			{
				if ((this._categories_id != value))
				{
					this.Oncategories_idChanging(value);
					this.SendPropertyChanging();
					this._categories_id = value;
					this.SendPropertyChanged("categories_id");
					this.Oncategories_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_language_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int language_id
		{
			get
			{
				return this._language_id;
			}
			set
			{
				if ((this._language_id != value))
				{
					this.Onlanguage_idChanging(value);
					this.SendPropertyChanging();
					this._language_id = value;
					this.SendPropertyChanged("language_id");
					this.Onlanguage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_name", DbType="NVarChar(62) NOT NULL", CanBeNull=false)]
		public string categories_name
		{
			get
			{
				return this._categories_name;
			}
			set
			{
				if ((this._categories_name != value))
				{
					this.Oncategories_nameChanging(value);
					this.SendPropertyChanging();
					this._categories_name = value;
					this.SendPropertyChanged("categories_name");
					this.Oncategories_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="categories_description", Storage="_categories_description1", DbType="NVarChar(MAX)")]
		public string categories_description1
		{
			get
			{
				return this._categories_description1;
			}
			set
			{
				if ((this._categories_description1 != value))
				{
					this.Oncategories_description1Changing(value);
					this.SendPropertyChanging();
					this._categories_description1 = value;
					this.SendPropertyChanged("categories_description1");
					this.Oncategories_description1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_url", DbType="NVarChar(62)")]
		public string categories_url
		{
			get
			{
				return this._categories_url;
			}
			set
			{
				if ((this._categories_url != value))
				{
					this.Oncategories_urlChanging(value);
					this.SendPropertyChanging();
					this._categories_url = value;
					this.SendPropertyChanged("categories_url");
					this.Oncategories_urlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ezpages")]
	public partial class ezpage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pages_id;
		
		private int _languages_id;
		
		private string _pages_title;
		
		private string _alt_url;
		
		private string _alt_url_external;
		
		private string _pages_html_text;
		
		private int _status_header;
		
		private int _status_sidebox;
		
		private int _status_footer;
		
		private int _status_toc;
		
		private int _header_sort_order;
		
		private int _sidebox_sort_order;
		
		private int _footer_sort_order;
		
		private int _toc_sort_order;
		
		private int _page_open_new_window;
		
		private int _page_is_ssl;
		
		private int _toc_chapter;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpages_idChanging(int value);
    partial void Onpages_idChanged();
    partial void Onlanguages_idChanging(int value);
    partial void Onlanguages_idChanged();
    partial void Onpages_titleChanging(string value);
    partial void Onpages_titleChanged();
    partial void Onalt_urlChanging(string value);
    partial void Onalt_urlChanged();
    partial void Onalt_url_externalChanging(string value);
    partial void Onalt_url_externalChanged();
    partial void Onpages_html_textChanging(string value);
    partial void Onpages_html_textChanged();
    partial void Onstatus_headerChanging(int value);
    partial void Onstatus_headerChanged();
    partial void Onstatus_sideboxChanging(int value);
    partial void Onstatus_sideboxChanged();
    partial void Onstatus_footerChanging(int value);
    partial void Onstatus_footerChanged();
    partial void Onstatus_tocChanging(int value);
    partial void Onstatus_tocChanged();
    partial void Onheader_sort_orderChanging(int value);
    partial void Onheader_sort_orderChanged();
    partial void Onsidebox_sort_orderChanging(int value);
    partial void Onsidebox_sort_orderChanged();
    partial void Onfooter_sort_orderChanging(int value);
    partial void Onfooter_sort_orderChanged();
    partial void Ontoc_sort_orderChanging(int value);
    partial void Ontoc_sort_orderChanged();
    partial void Onpage_open_new_windowChanging(int value);
    partial void Onpage_open_new_windowChanged();
    partial void Onpage_is_sslChanging(int value);
    partial void Onpage_is_sslChanged();
    partial void Ontoc_chapterChanging(int value);
    partial void Ontoc_chapterChanged();
    #endregion
		
		public ezpage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pages_id
		{
			get
			{
				return this._pages_id;
			}
			set
			{
				if ((this._pages_id != value))
				{
					this.Onpages_idChanging(value);
					this.SendPropertyChanging();
					this._pages_id = value;
					this.SendPropertyChanged("pages_id");
					this.Onpages_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_languages_id", DbType="Int NOT NULL")]
		public int languages_id
		{
			get
			{
				return this._languages_id;
			}
			set
			{
				if ((this._languages_id != value))
				{
					this.Onlanguages_idChanging(value);
					this.SendPropertyChanging();
					this._languages_id = value;
					this.SendPropertyChanged("languages_id");
					this.Onlanguages_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_title", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string pages_title
		{
			get
			{
				return this._pages_title;
			}
			set
			{
				if ((this._pages_title != value))
				{
					this.Onpages_titleChanging(value);
					this.SendPropertyChanging();
					this._pages_title = value;
					this.SendPropertyChanged("pages_title");
					this.Onpages_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alt_url", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string alt_url
		{
			get
			{
				return this._alt_url;
			}
			set
			{
				if ((this._alt_url != value))
				{
					this.Onalt_urlChanging(value);
					this.SendPropertyChanging();
					this._alt_url = value;
					this.SendPropertyChanged("alt_url");
					this.Onalt_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alt_url_external", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string alt_url_external
		{
			get
			{
				return this._alt_url_external;
			}
			set
			{
				if ((this._alt_url_external != value))
				{
					this.Onalt_url_externalChanging(value);
					this.SendPropertyChanging();
					this._alt_url_external = value;
					this.SendPropertyChanged("alt_url_external");
					this.Onalt_url_externalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pages_html_text", DbType="NVarChar(MAX)")]
		public string pages_html_text
		{
			get
			{
				return this._pages_html_text;
			}
			set
			{
				if ((this._pages_html_text != value))
				{
					this.Onpages_html_textChanging(value);
					this.SendPropertyChanging();
					this._pages_html_text = value;
					this.SendPropertyChanged("pages_html_text");
					this.Onpages_html_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_header", DbType="Int NOT NULL")]
		public int status_header
		{
			get
			{
				return this._status_header;
			}
			set
			{
				if ((this._status_header != value))
				{
					this.Onstatus_headerChanging(value);
					this.SendPropertyChanging();
					this._status_header = value;
					this.SendPropertyChanged("status_header");
					this.Onstatus_headerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_sidebox", DbType="Int NOT NULL")]
		public int status_sidebox
		{
			get
			{
				return this._status_sidebox;
			}
			set
			{
				if ((this._status_sidebox != value))
				{
					this.Onstatus_sideboxChanging(value);
					this.SendPropertyChanging();
					this._status_sidebox = value;
					this.SendPropertyChanged("status_sidebox");
					this.Onstatus_sideboxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_footer", DbType="Int NOT NULL")]
		public int status_footer
		{
			get
			{
				return this._status_footer;
			}
			set
			{
				if ((this._status_footer != value))
				{
					this.Onstatus_footerChanging(value);
					this.SendPropertyChanging();
					this._status_footer = value;
					this.SendPropertyChanged("status_footer");
					this.Onstatus_footerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_toc", DbType="Int NOT NULL")]
		public int status_toc
		{
			get
			{
				return this._status_toc;
			}
			set
			{
				if ((this._status_toc != value))
				{
					this.Onstatus_tocChanging(value);
					this.SendPropertyChanging();
					this._status_toc = value;
					this.SendPropertyChanged("status_toc");
					this.Onstatus_tocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_header_sort_order", DbType="Int NOT NULL")]
		public int header_sort_order
		{
			get
			{
				return this._header_sort_order;
			}
			set
			{
				if ((this._header_sort_order != value))
				{
					this.Onheader_sort_orderChanging(value);
					this.SendPropertyChanging();
					this._header_sort_order = value;
					this.SendPropertyChanged("header_sort_order");
					this.Onheader_sort_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sidebox_sort_order", DbType="Int NOT NULL")]
		public int sidebox_sort_order
		{
			get
			{
				return this._sidebox_sort_order;
			}
			set
			{
				if ((this._sidebox_sort_order != value))
				{
					this.Onsidebox_sort_orderChanging(value);
					this.SendPropertyChanging();
					this._sidebox_sort_order = value;
					this.SendPropertyChanged("sidebox_sort_order");
					this.Onsidebox_sort_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_footer_sort_order", DbType="Int NOT NULL")]
		public int footer_sort_order
		{
			get
			{
				return this._footer_sort_order;
			}
			set
			{
				if ((this._footer_sort_order != value))
				{
					this.Onfooter_sort_orderChanging(value);
					this.SendPropertyChanging();
					this._footer_sort_order = value;
					this.SendPropertyChanged("footer_sort_order");
					this.Onfooter_sort_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toc_sort_order", DbType="Int NOT NULL")]
		public int toc_sort_order
		{
			get
			{
				return this._toc_sort_order;
			}
			set
			{
				if ((this._toc_sort_order != value))
				{
					this.Ontoc_sort_orderChanging(value);
					this.SendPropertyChanging();
					this._toc_sort_order = value;
					this.SendPropertyChanged("toc_sort_order");
					this.Ontoc_sort_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_open_new_window", DbType="Int NOT NULL")]
		public int page_open_new_window
		{
			get
			{
				return this._page_open_new_window;
			}
			set
			{
				if ((this._page_open_new_window != value))
				{
					this.Onpage_open_new_windowChanging(value);
					this.SendPropertyChanging();
					this._page_open_new_window = value;
					this.SendPropertyChanged("page_open_new_window");
					this.Onpage_open_new_windowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_is_ssl", DbType="Int NOT NULL")]
		public int page_is_ssl
		{
			get
			{
				return this._page_is_ssl;
			}
			set
			{
				if ((this._page_is_ssl != value))
				{
					this.Onpage_is_sslChanging(value);
					this.SendPropertyChanging();
					this._page_is_ssl = value;
					this.SendPropertyChanged("page_is_ssl");
					this.Onpage_is_sslChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toc_chapter", DbType="Int NOT NULL")]
		public int toc_chapter
		{
			get
			{
				return this._toc_chapter;
			}
			set
			{
				if ((this._toc_chapter != value))
				{
					this.Ontoc_chapterChanging(value);
					this.SendPropertyChanging();
					this._toc_chapter = value;
					this.SendPropertyChanged("toc_chapter");
					this.Ontoc_chapterChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categories")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _categories_id;
		
		private string _categories_image;
		
		private int _parent_id;
		
		private System.Nullable<int> _sort_order;
		
		private System.Nullable<System.DateTime> _date_added;
		
		private System.Nullable<System.DateTime> _last_modified;
		
		private short _categories_status;
		
		private System.Nullable<int> _home_order;
		
		private System.Nullable<int> _cate_level;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategories_idChanging(int value);
    partial void Oncategories_idChanged();
    partial void Oncategories_imageChanging(string value);
    partial void Oncategories_imageChanged();
    partial void Onparent_idChanging(int value);
    partial void Onparent_idChanged();
    partial void Onsort_orderChanging(System.Nullable<int> value);
    partial void Onsort_orderChanged();
    partial void Ondate_addedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_addedChanged();
    partial void Onlast_modifiedChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_modifiedChanged();
    partial void Oncategories_statusChanging(short value);
    partial void Oncategories_statusChanged();
    partial void Onhome_orderChanging(System.Nullable<int> value);
    partial void Onhome_orderChanged();
    partial void Oncate_levelChanging(System.Nullable<int> value);
    partial void Oncate_levelChanged();
    #endregion
		
		public category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int categories_id
		{
			get
			{
				return this._categories_id;
			}
			set
			{
				if ((this._categories_id != value))
				{
					this.Oncategories_idChanging(value);
					this.SendPropertyChanging();
					this._categories_id = value;
					this.SendPropertyChanged("categories_id");
					this.Oncategories_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_image", DbType="NVarChar(64)")]
		public string categories_image
		{
			get
			{
				return this._categories_image;
			}
			set
			{
				if ((this._categories_image != value))
				{
					this.Oncategories_imageChanging(value);
					this.SendPropertyChanging();
					this._categories_image = value;
					this.SendPropertyChanged("categories_image");
					this.Oncategories_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_id", DbType="Int NOT NULL")]
		public int parent_id
		{
			get
			{
				return this._parent_id;
			}
			set
			{
				if ((this._parent_id != value))
				{
					this.Onparent_idChanging(value);
					this.SendPropertyChanging();
					this._parent_id = value;
					this.SendPropertyChanged("parent_id");
					this.Onparent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_order", DbType="Int")]
		public System.Nullable<int> sort_order
		{
			get
			{
				return this._sort_order;
			}
			set
			{
				if ((this._sort_order != value))
				{
					this.Onsort_orderChanging(value);
					this.SendPropertyChanging();
					this._sort_order = value;
					this.SendPropertyChanged("sort_order");
					this.Onsort_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_added", DbType="DateTime2")]
		public System.Nullable<System.DateTime> date_added
		{
			get
			{
				return this._date_added;
			}
			set
			{
				if ((this._date_added != value))
				{
					this.Ondate_addedChanging(value);
					this.SendPropertyChanging();
					this._date_added = value;
					this.SendPropertyChanged("date_added");
					this.Ondate_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_modified", DbType="DateTime2")]
		public System.Nullable<System.DateTime> last_modified
		{
			get
			{
				return this._last_modified;
			}
			set
			{
				if ((this._last_modified != value))
				{
					this.Onlast_modifiedChanging(value);
					this.SendPropertyChanging();
					this._last_modified = value;
					this.SendPropertyChanged("last_modified");
					this.Onlast_modifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_status", DbType="SmallInt NOT NULL")]
		public short categories_status
		{
			get
			{
				return this._categories_status;
			}
			set
			{
				if ((this._categories_status != value))
				{
					this.Oncategories_statusChanging(value);
					this.SendPropertyChanging();
					this._categories_status = value;
					this.SendPropertyChanged("categories_status");
					this.Oncategories_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_order", DbType="Int")]
		public System.Nullable<int> home_order
		{
			get
			{
				return this._home_order;
			}
			set
			{
				if ((this._home_order != value))
				{
					this.Onhome_orderChanging(value);
					this.SendPropertyChanging();
					this._home_order = value;
					this.SendPropertyChanged("home_order");
					this.Onhome_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_level", DbType="Int")]
		public System.Nullable<int> cate_level
		{
			get
			{
				return this._cate_level;
			}
			set
			{
				if ((this._cate_level != value))
				{
					this.Oncate_levelChanging(value);
					this.SendPropertyChanging();
					this._cate_level = value;
					this.SendPropertyChanged("cate_level");
					this.Oncate_levelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
